// Regenerate frontend/.ds-kit/kit.css = Google-Fonts @import (harvested from
// frontend/index.html, where the real app loads its faction webfonts via a
// <link>) prepended to the TAILWIND-COMPILED frontend/src/index.css.
//
// Why compile Tailwind: index.css is just `@tailwind base/components/utilities`
// + the app's custom vars/rules. The design-sync converter copies cssEntry
// verbatim — it does NOT run PostCSS — so without this step the @tailwind
// directives pass through as no-ops and every component that uses a utility
// class (rounded-full, object-cover, flex, …) renders unstyled. We run the
// repo's own Tailwind (scanning src/ per tailwind.config.ts) to emit exactly
// the utilities the components use, then cssEntry points at the result.
//
// kit.css + index.compiled.css are gitignored (derived); re-run before each
// design-sync build:  node .design-sync/gen-kit-css.mjs
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

// 1. Compile Tailwind over the app's real entry stylesheet (cwd = frontend so
//    the config's ./src/** content globs and node_modules resolve).
execFileSync(
  process.execPath,
  ['node_modules/tailwindcss/lib/cli.js', '-c', 'tailwind.config.ts', '-i', 'src/index.css', '-o', '.ds-kit/index.compiled.css', '--minify'],
  { cwd: 'frontend', stdio: 'inherit' },
);

// 2. Prepend the Google-Fonts @import (must be the first at-rule).
const html = readFileSync('frontend/index.html', 'utf8');
const href = html.match(/href="(https:\/\/fonts\.googleapis\.com\/css2[^"]+)"/)?.[1];
if (!href) throw new Error('no Google Fonts <link> href in frontend/index.html');
const compiled = readFileSync('frontend/.ds-kit/index.compiled.css', 'utf8');

writeFileSync(
  'frontend/.ds-kit/kit.css',
  `/* AUTO-GENERATED by .design-sync/gen-kit-css.mjs — do not edit. */\n` +
    `@import url('${href}');\n` +
    compiled +
    '\n',
);
console.error('wrote frontend/.ds-kit/kit.css (tailwind-compiled + webfonts)');
