#!/usr/bin/env node
/**
 * Regenerates the self-hosted font kit: `src/assets/fonts/*.woff2`,
 * `src/fonts.css`, `src/fonts.faction.css` and
 * `src/assets/fonts/licences/*` (#1977, #2079).
 *
 * WHY THIS IS A SCRIPT AND NOT A HAND-WRITTEN STYLESHEET
 * -----------------------------------------------------
 * The two sheets are ~80 `@font-face` blocks carrying opaque `unicode-range`
 * strings and content-addressed file names. Hand-editing them is how a `src:`
 * path drifts one character from the file on disk, and a wrong `src:` does not
 * throw — the family silently resolves to generic serif, which is exactly the
 * failure `docs/agents/design-fidelity.md` records from the #821 wave. So the
 * stylesheets are generated from FACES below, and `fontsLoaded.test.ts` asserts
 * the generated files agree with what the app's CSS actually asks for.
 *
 * TWO SHEETS, AND WHICH ONE A RULE LANDS IN IS DECIDED BY SHELL_FAMILIES (#2079).
 * `src/fonts.css` is `@import`ed by index.css, so it is the render-blocking half
 * and holds only the three families the app shell renders in. Everything else
 * goes to `src/fonts.faction.css`, which nothing @imports: `src/factionFaces.ts`
 * is its only importer, reached across a chunk boundary, so Vite emits it as a
 * separate CSS asset that dist/index.html never mentions.
 *
 * FACES IS THE SOURCE OF TRUTH FOR WHAT WE SHIP.
 * It is the axis spec that used to live in the Google Fonts `<link>` in
 * index.html, moved here verbatim. Do NOT edit it by eye: the two guards in
 * `fontsLoaded.test.ts` derive the needed set from the stylesheets and will
 * tell you what to add or drop. Re-run this script after changing it.
 *
 * Usage: node scripts/fetch-fonts.mjs
 * Needs network access to fonts.googleapis.com, fonts.gstatic.com and
 * raw.githubusercontent.com. It is a maintenance script, never part of `build`.
 */
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const FRONTEND = join(dirname(fileURLToPath(import.meta.url)), '..')
const FONT_DIR = join(FRONTEND, 'src', 'assets', 'fonts')
const LICENCE_DIR = join(FONT_DIR, 'licences')
const SHELL_CSS_PATH = join(FRONTEND, 'src', 'fonts.css')
const FACTION_CSS_PATH = join(FRONTEND, 'src', 'fonts.faction.css')

/**
 * The families the app SHELL renders in, and therefore the only ones allowed in
 * the render-blocking sheet (#2079).
 *
 * They are the `--font-display` / `--font-body` / `--font-accent` families, which
 * are also Tailwind's three family utilities, so any neutral page, the nav and
 * the sidebar can render in them — none of which is behind a chunk boundary.
 * Every other family reaches the page through a faction surface.
 *
 * MOVING A FAMILY BETWEEN THE SHEETS IS NOT A TUNING. Into this set and it costs
 * every visitor on every route the bytes; out of it and any surface whose chunk
 * cannot reach `src/factionFaces.ts` renders in a generic fallback, silently,
 * because `font-display: swap` means the fallback IS the rendering (#839).
 * `factionFaceSplit.test.ts` holds both halves of that boundary.
 */
const SHELL_FAMILIES = new Set(['Lora', 'Courier Prime', 'Bebas Neue'])

/** Header of the render-blocking sheet. */
const SHELL_HEADER = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand (#1977, #2079).
 *
 * THE SHELL'S THREE FAMILIES — and the only @font-face rules on the critical
 * path. index.css @imports this file, so everything here lands in the one
 * render-blocking stylesheet. The kit's other 15 families are in
 * \`fonts.faction.css\`, fetched by a faction chunk instead (#2079).
 *
 * Lora (--font-display), Courier Prime (--font-body) and Bebas Neue
 * (--font-accent) are the app chrome: the nav, the sidebar, every neutral page,
 * and Tailwind's three family utilities. A family belongs in THIS file when a
 * module statically reachable from \`main.tsx\` can render in it —
 * \`factionFaceSplit.test.ts\` asserts that boundary in both directions, because
 * a family in the wrong sheet does not fail, it paints a fallback and swaps.
 *
 * They used to come from a render-blocking third-party <link> in index.html,
 * which cost a DNS + TCP + TLS handshake to two Google origins before first
 * paint, sent every viewer's IP to that third party, and could not be given
 * immutable cache headers. These are content-hashed into /assets by Vite, which
 * render.yaml serves 'immutable'.
 *
 * font-display: swap is carried over verbatim from the old '&display=swap'
 * URL. It is the only value that keeps rendering identical: text paints in the
 * fallback immediately and swaps when the face arrives. 'optional' would let a
 * first-time visitor keep the fallback for the whole page load, which on a site
 * where the face IS the faction's identity is a visible change, not a tuning.
 *
 * Every family also keeps Google's own 'unicode-range', so a browser still
 * downloads only the cuts a page's glyphs actually need.
 *
 * Licences ship alongside the fonts in src/assets/fonts/licences/ and are
 * credited on the Attributions page. Do not strip them.
 *
 * Regenerate: node scripts/fetch-fonts.mjs
 */
`

/** Header of the lazily-fetched sheet. */
const FACTION_HEADER = `/* GENERATED by scripts/fetch-fonts.mjs — do not edit by hand (#1977, #2079).
 *
 * THE 15 FACTION FAMILIES, OFF THE CRITICAL PATH. Nothing @imports this file.
 * \`src/factionFaces.ts\` is its only importer, and that module is reached only by
 * dynamic import — from \`factions/lazyArchetype.tsx\`, which every faction
 * archetype loads through, and from the handful of lazy route modules that draw
 * a faction face without dispatching an archetype. Vite therefore emits it as a
 * separate CSS asset attached to an async chunk, and dist/index.html never
 * mentions it.
 *
 * Why (#2079): all 82 rules used to sit in \`fonts.css\`, so 62 of them blocked
 * first paint for faces only a faction surface can render in — ~19% of the
 * blocking stylesheet, on a budget with 774 bytes of headroom. The shell renders
 * in exactly three families and those stayed behind in \`fonts.css\`.
 *
 * The failure mode of getting the split wrong is a fallback flash, not invisible
 * text — every rule here carries font-display: swap, which is already the cold
 * first-load behaviour. That makes it invisible in review, so
 * \`factionFaceSplit.test.ts\` guards the boundary from the module graph rather
 * than from a screenshot.
 *
 * Every family keeps Google's own 'unicode-range', so a browser still downloads
 * only the cuts a page's glyphs actually need.
 *
 * The last three rules are different in kind (#2038, widened by #2148): three
 * Noto faces subset to EXACTLY THE CODEPOINTS \`src/locales/en/glosses.json\`
 * casts the Ephemerists' labels in, and to nothing else. Their 'unicode-range'
 * is therefore the literal list of those characters, so a page that prints none
 * of them fetches none of them.
 *
 * Licences ship alongside the fonts in src/assets/fonts/licences/ and are
 * credited on the Attributions page. Do not strip them.
 *
 * Regenerate: node scripts/fetch-fonts.mjs
 */
`

/**
 * The 18 families and their axis specs, exactly as the retired Google Fonts
 * `<link>` requested them — 41 faces. That set was already minimal in both
 * directions when this landed: #1230's guard had removed every face nothing
 * renders in, and #1294's had added every weight a stylesheet sets. So this is
 * a DELIVERY change, not a type change; the face list is unchanged on purpose.
 */
const FACES = [
  'Anton',
  'Archivo+Black',
  'Lora:ital,wght@0,400;0,600;0,700;1,400;1,500;1,600;1,700',
  'Courier+Prime:wght@400;700',
  'Special+Elite',
  'Share+Tech+Mono',
  'Bebas+Neue',
  'Permanent+Marker',
  'Caveat:wght@400;700',
  'MedievalSharp',
  'IM+Fell+English:ital@1',
  'Cinzel:wght@400;500;600;700;800',
  'EB+Garamond:ital,wght@0,400;0,600;1,400',
  'Cormorant+Garamond:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600',
  'Quicksand:wght@400;700',
  'Grenze+Gotisch:wght@400;600',
  'Poiret+One',
  'Spectral:ital,wght@0,400;1,400',
]

/**
 * Which of Google's per-subset cuts we keep.
 *
 * Google slices every face into up to nine subsets (cyrillic, greek, math,
 * symbols, vietnamese…) each behind a `unicode-range`, and a browser downloads
 * only the ones a page's glyphs fall in. Keeping the ranges means self-hosting
 * inherits that laziness: an English page still fetches only `latin`.
 *
 * ponytail: latin + latin-ext is the ceiling here. The catalogue is `en` only
 * and user copy is Latin-script, so the dropped subsets were never fetched in
 * practice — but a name in Cyrillic would now fall back to the generic stack
 * for those glyphs rather than render in the faction face. Upgrade path is one
 * more entry in this array plus a re-run; nothing else changes.
 */
const KEEP_SUBSETS = new Set(['latin', 'latin-ext'])

/**
 * Faces subset to a LITERAL STRING rather than to Google's subset cuts (#2038).
 *
 * The Ephemerists task card turns its points label and its sign-up through five
 * scripts, and the repo carries no Noto family. Taking these the normal way is
 * not an option at either end: Google slices Noto Serif JP into ~120 cuts, so
 * `FACES` above would add ~120 `@font-face` rules to a render-blocking
 * stylesheet that has 1.6 KB of headroom, and the design's system fallback
 * chain (`Geeza Pro`, `Hiragino Mincho ProN`, `Segoe UI Historic`) fails
 * asymmetrically by platform — cuneiform is tofu on Linux and Android while a
 * Mac reviewer sees nothing wrong.
 *
 * So these three use the v1 API's `text=` parameter, which returns ONE
 * @font-face over a font containing only the requested codepoints. A few dozen
 * codepoints across three faces; the woff2 files are single-digit KB each,
 * against ~4 MB for Noto Serif JP whole.
 *
 * `text` IS THE CONTRACT WITH THE CATALOG, so it is not written out: it is
 * derived from `src/locales/en/glosses.json`, which is the ONE place the kit's
 * casts live (#2148). A character dropped here does not throw — it renders as
 * tofu, which on a task card is indistinguishable from a bug — and a hand-kept
 * second list of the same characters is precisely how that happens. Adding a
 * word to the catalog is therefore the whole edit; re-running this script is
 * the whole follow-up, and
 * `src/components/factionMarks/__tests__/ephemeristsScriptTurn.test.tsx` fails
 * until it has been done, by reading the casts out of the catalog and checking
 * them against the `unicode-range` these rules ship.
 */
const GLOSS_FAMILIES = {
  arabic: 'Noto Naskh Arabic',
  japanese: 'Noto Serif JP',
  cuneiform: 'Noto Sans Cuneiform',
}

const GLOSSES = JSON.parse(
  readFileSync(join(FRONTEND, 'src', 'locales', 'en', 'glosses.json'), 'utf-8'),
)

const TEXT_FACES = Object.entries(GLOSS_FAMILIES).map(([script, family]) => ({
  family,
  // Dedupe by CODE POINT — spreading a string iterates code points, so a
  // cuneiform sign outside the BMP stays one character rather than two halves.
  text: [
    ...new Set(Object.values(GLOSSES).flatMap((word) => [...word[script]])),
  ].join(''),
}))

/** A desktop UA, or Google serves the ttf/woff cuts instead of woff2. */
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

/**
 * Licence file per family, fetched from the google/fonts catalogue.
 *
 * As it stands: 16 of the 18 are OFL 1.1 under `ofl/`, and Permanent Marker and
 * Special Elite are Apache 2.0 under `apache/`. The script does not hardcode
 * that split — it walks the roots and THROWS if a family yields no licence,
 * because a font shipped without one is the one failure here that is a legal
 * problem rather than a visual one, and it would otherwise be invisible.
 */
const LICENCE_ROOTS = ['ofl', 'apache', 'ufl']
const LICENCE_NAMES = ['OFL.txt', 'LICENSE.txt', 'UFL.txt']

const slug = (family) => family.toLowerCase().replace(/[^a-z0-9]+/g, '-')
const catalogueDir = (family) => family.toLowerCase().replace(/[^a-z0-9]+/g, '')

async function text(url) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!response.ok) throw new Error(`${response.status} ${url}`)
  return response.text()
}

/** `@font-face { … }` blocks, each tagged with the `/* subset *\/` above it. */
function parseBlocks(css) {
  const blocks = []
  let subset = 'latin'
  for (const chunk of css.split('@font-face')) {
    const comment = [...chunk.matchAll(/\/\*\s*([a-z-]+)\s*\*\//g)].pop()
    const body = chunk.match(/\{([\s\S]*?)\}/)
    if (body) blocks.push({ subset, body: body[1] })
    if (comment) subset = comment[1]
  }
  return blocks
}

const field = (body, name) => body.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim()

/**
 * The code points a `unicode-range` value covers. Only ever called on the
 * literal-string subsets, whose ranges are ten code points long — expanding a
 * `U+0-10FFFF` would not be sane, so it refuses one.
 */
function codePointsIn(range) {
  const points = new Set()
  for (const part of range.split(',')) {
    const [from, to] = part.trim().replace(/^u\+/i, '').split('-')
    const start = parseInt(from, 16)
    const end = to === undefined ? start : parseInt(to, 16)
    if (!(end - start < 64)) throw new Error(`unicode-range ${part} is not a subset`)
    for (let point = start; point <= end; point++) points.add(point)
  }
  return points
}

/** The licence ships with the font — see either generated sheet's header. */
async function fetchLicence(family) {
  let licence
  for (const root of LICENCE_ROOTS) {
    for (const name of LICENCE_NAMES) {
      if (licence) continue
      licence = await text(
        `https://raw.githubusercontent.com/google/fonts/main/${root}/${catalogueDir(family)}/${name}`,
      ).catch(() => undefined)
      if (licence) {
        writeFileSync(join(LICENCE_DIR, `${slug(family)}-${name}`), licence)
      }
    }
  }
  if (!licence) throw new Error(`no licence found for ${family}`)
}

async function main() {
  rmSync(FONT_DIR, { recursive: true, force: true })
  mkdirSync(LICENCE_DIR, { recursive: true })

  const rules = []
  let bytes = 0

  for (const spec of FACES) {
    const family = decodeURIComponent(spec.split(':')[0]).replace(/\+/g, ' ')
    const css = await text(
      `https://fonts.googleapis.com/css2?family=${spec}&display=swap`,
    )
    const kept = parseBlocks(css).filter((block) => KEEP_SUBSETS.has(block.subset))
    if (kept.length === 0) throw new Error(`no latin cut for ${family}`)

    const cuts = kept.map(({ subset, body }) => ({
      subset,
      weight: field(body, 'font-weight') ?? '400',
      style: field(body, 'font-style') ?? 'normal',
      range: field(body, 'unicode-range'),
      source: field(body, 'src')?.match(/url\(([^)]+)\)/)?.[1],
    }))
    if (cuts.some((cut) => !cut.source)) throw new Error(`a cut of ${family} has no src`)

    // Google serves ONE variable woff2 per (family, slant, subset) and points
    // every requested weight at it — Cinzel's five weights are five @font-face
    // rules over a single file. Downloading per rule would carry 36 byte-identical
    // duplicates (1.15 MB) in git; Vite would dedupe them on the way out, so the
    // waste would be invisible in dist and permanent in the repo. Group by the
    // gstatic URL, which IS the file's identity.
    const groups = new Map()
    for (const cut of cuts) {
      const group = groups.get(cut.source) ?? { ...cut, weights: [] }
      group.weights.push(cut.weight)
      groups.set(cut.source, group)
    }

    for (const group of groups.values()) {
      const { subset, style, range, source, weights } = group
      const numeric = weights.map(Number).sort((a, b) => a - b)
      // A shared file is the variable font over that whole range, and saying so
      // in the name is the difference between `cinzel-400to800-latin.woff2` and
      // a `cinzel-400-latin.woff2` that four other rules quietly also point at.
      const cut =
        numeric.length > 1 ? `${numeric[0]}to${numeric.at(-1)}` : `${numeric[0]}`
      const file = `${slug(family)}-${cut}${style === 'italic' ? 'i' : ''}-${subset}.woff2`
      const woff2 = Buffer.from(
        await (await fetch(source, { headers: { 'User-Agent': UA } })).arrayBuffer(),
      )
      if (woff2.length < 1000) throw new Error(`suspiciously small ${file}`)
      writeFileSync(join(FONT_DIR, file), woff2)
      bytes += woff2.length

      for (const weight of weights) {
        rules.push({
          family,
          css:
          `/* ${family} ${weight}${style === 'italic' ? ' italic' : ''} — ${subset} */\n` +
            `@font-face {\n` +
            `  font-family: '${family}';\n` +
            `  font-style: ${style};\n` +
            `  font-weight: ${weight};\n` +
            `  font-display: swap;\n` +
            `  src: url('./assets/fonts/${file}') format('woff2');\n` +
            (range ? `  unicode-range: ${range};\n` : '') +
            `}`,
        })
      }
    }

    await fetchLicence(family)
    console.log(`${family.padEnd(20)} ${kept.length} cut(s)`)
  }

  // The literal-string subsets (#2038). Same file naming, same licence rule,
  // one rule each — only the request differs, so this is a short second pass
  // rather than a branch through the loop above.
  for (const { family, text: characters } of TEXT_FACES) {
    const css = await text(
      `https://fonts.googleapis.com/css?family=${encodeURIComponent(family)}` +
        `&text=${encodeURIComponent(characters)}`,
    )
    const [block] = parseBlocks(css)
    if (!block) throw new Error(`no @font-face for ${family}`)
    const source = field(block.body, 'src')?.match(/url\(([^)]+)\)/)?.[1]
    const range = field(block.body, 'unicode-range')
    if (!source) throw new Error(`the ${family} subset has no src`)
    // The whole point of this pass is that the face carries exactly the
    // characters asked for. Compare CODE POINTS, not commas: Google collapses
    // adjacent ones (`U+642-643`), so counting the list would be off by
    // however many happened to be neighbours.
    const covered = codePointsIn(range ?? '')
    const wanted = new Set([...characters].map((character) => character.codePointAt(0)))
    if ([...wanted].some((point) => !covered.has(point))) {
      throw new Error(`${family} came back covering ${range}, not ${characters}`)
    }

    const file = `${slug(family)}-400-subset.woff2`
    const woff2 = Buffer.from(
      await (await fetch(source, { headers: { 'User-Agent': UA } })).arrayBuffer(),
    )
    if (woff2.length < 400) throw new Error(`suspiciously small ${file}`)
    writeFileSync(join(FONT_DIR, file), woff2)
    bytes += woff2.length

    rules.push({
      family,
      css:
        `/* ${family} 400 — subset to '${characters}' (#2038) */\n` +
        `@font-face {\n` +
        `  font-family: '${family}';\n` +
        `  font-style: normal;\n` +
        `  font-weight: 400;\n` +
        `  font-display: swap;\n` +
        `  src: url('./assets/fonts/${file}') format('woff2');\n` +
        `  unicode-range: ${range};\n` +
        `}`,
    })
    await fetchLicence(family)
    console.log(`${family.padEnd(20)} 1 subset cut (${woff2.length} B)`)
  }

  const shell = rules.filter((rule) => SHELL_FAMILIES.has(rule.family))
  const faction = rules.filter((rule) => !SHELL_FAMILIES.has(rule.family))
  // A sheet with no rules would be an empty @import or a chunk with no CSS —
  // green, and wrong in the direction nobody looks at.
  if (shell.length === 0 || faction.length === 0) {
    throw new Error(`SHELL_FAMILIES matched ${shell.length} of ${rules.length} rules`)
  }

  writeFileSync(
    SHELL_CSS_PATH,
    `${SHELL_HEADER}\n${shell.map((rule) => rule.css).join('\n\n')}\n`,
  )
  writeFileSync(
    FACTION_CSS_PATH,
    `${FACTION_HEADER}\n${faction.map((rule) => rule.css).join('\n\n')}\n`,
  )

  const files = readdirSync(FONT_DIR).filter((name) => name.endsWith('.woff2'))
  console.log(`\n${files.length} woff2 files, ${(bytes / 1024).toFixed(1)} KB on disk`)
  console.log(`${shell.length} @font-face rules -> src/fonts.css (render-blocking)`)
  console.log(`${faction.length} @font-face rules -> src/fonts.faction.css (lazy)`)
}

await main()
