"""Persist a praxis room's CRDT document: ``praxis_room_update`` (#1740, ADR-0073).

A room is in-process and dies with its last connection; this table is what lets
the document outlive it. Without it, reopening a room would re-seed from
``praxis.body_text`` and the seed-once rule would be broken by the back door —
the same duplication footgun, one restart later. See ``models/praxis_room.py``.

``ON DELETE CASCADE`` matches every other praxis child (``0006``): the draft is
part of the praxis, and CRDT history keeps tombstones — text the author deleted
— which must not outlive the draft it was deleted from.

``0002_squashed`` builds a *fresh* database straight from the ORM models, so CI
and local resets already land on this shape. A deployed database is stamped at
an earlier revision and never re-runs it — hence this one. Idempotent either
way.

Revision ID: 0008_praxis_room_update
Revises: 0007_oauth_provider_unique
Create Date: 2026-08-14
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0008_praxis_room_update"
down_revision: Union[str, None] = "0007_oauth_provider_unique"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS praxis_room_update (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            praxis_id BIGINT NOT NULL,
            "update" BYTEA NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_praxis_room_update PRIMARY KEY (id),
            CONSTRAINT fk_praxis_room_update_praxis_id_praxis
                FOREIGN KEY (praxis_id) REFERENCES praxis (id) ON DELETE CASCADE
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_praxis_room_update_praxis_id_id "
        "ON praxis_room_update (praxis_id, id)"
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS praxis_room_update")
