"""The consent log: ``terms_acceptance`` (#1861, SPEC-onboarding § Terms).

One row per time an account agreed to the terms. Append-only by design, so
there is deliberately **no** unique constraint on ``account_id`` — a second
acceptance is a second event, not a duplicate. See ``models/terms_acceptance.py``.

No backfill. Accounts that predate this table have no rows, which is the honest
record: nobody was ever shown the document.

No index either. The only read this table has today is the insert's own
``RETURNING``; whether a future version bump gates established players is out
of scope for the onboarding arc, and that is the query an index would be for.

``0002_squashed`` builds a *fresh* database straight from the ORM models, so CI
and local resets already land on this shape. A deployed database is stamped at
an earlier revision and never re-runs it — hence this one. Idempotent either
way.

Revision ID: 0010_terms_acceptance
Revises: 0009_task_notes
Create Date: 2026-08-16
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0010_terms_acceptance"
down_revision: Union[str, None] = "0009_task_notes"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS terms_acceptance (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            account_id BIGINT NOT NULL,
            version VARCHAR(32) NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_terms_acceptance PRIMARY KEY (id),
            CONSTRAINT fk_terms_acceptance_account_id_account
                FOREIGN KEY (account_id) REFERENCES account (id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS terms_acceptance")
