"""The block record, and the blocked edges that migrate into it (ADR-0077, #1906).

Schema **and** data, in that order.

Schema: ``character_block``, one row per ordered (blocker, blocked) pair. See
``models/character_block.py`` for why the cascade and the self-block CHECK are
configured now rather than retrofitted.

Data (ADR-0077 ruling 4): every ``relationship`` row with ``status = 'blocked'``
becomes one block record, ``from_character_id`` → ``to_character_id``, **and the
edge is deleted** — not returned to ``active``. Under the old model that edge
was frequently only the block's carrier: the declaration a player had to make in
order to reach the block button. Restoring it would resurrect a friend or foe
declaration made for a reason that no longer exists. Where the declaration was
meant, the player can make it again; a migration cannot tell the two apart, and
the cheaper mistake is to drop it.

**This is not reversible by redeploying.** ``downgrade()`` puts the edges back as
``foe``/``blocked`` — which is a guess, because the type the player originally
declared is gone with the row. The block records themselves round-trip exactly.

``RelationshipStatus.blocked`` stays on the ``relationshipstatus`` enum,
unwritten and unread: dropping a value from a PG enum needs a type swap and a
table rewrite, and buys nothing (ruling 3).

``0002_squashed`` builds a *fresh* database straight from the ORM models, so CI
and local resets already have this table by the time this revision runs — hence
``IF NOT EXISTS``, and hence a data step that finds nothing there. A deployed
database is stamped at an earlier revision and gets both halves.

Revision ID: 0012_character_block
Revises: 0011_character_departed_at
Create Date: 2026-08-16
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0012_character_block"
down_revision: Union[str, None] = "0011_character_departed_at"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS character_block (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY,
            blocker_character_id BIGINT NOT NULL,
            blocked_character_id BIGINT NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT pk_character_block PRIMARY KEY (id),
            CONSTRAINT uq_character_block_blocker_character_id_blocked_character_id
                UNIQUE (blocker_character_id, blocked_character_id),
            CONSTRAINT ck_character_block_no_self_block
                CHECK (blocker_character_id <> blocked_character_id),
            CONSTRAINT fk_character_block_blocker_character_id_character
                FOREIGN KEY (blocker_character_id) REFERENCES character (id)
                ON DELETE CASCADE,
            CONSTRAINT fk_character_block_blocked_character_id_character
                FOREIGN KEY (blocked_character_id) REFERENCES character (id)
                ON DELETE CASCADE
        )
        """
    )
    # ON CONFLICT DO NOTHING because the pair is unique but the old model's
    # unique constraint was per-edge: A→B blocked and B→A blocked are two edges
    # and two *different* ordered pairs, so they both survive as records — but a
    # re-run of this revision must not raise.
    op.execute(
        """
        INSERT INTO character_block (blocker_character_id, blocked_character_id)
        SELECT from_character_id, to_character_id
        FROM relationship
        WHERE status = 'blocked'
        ON CONFLICT DO NOTHING
        """
    )
    op.execute("DELETE FROM relationship WHERE status = 'blocked'")


def downgrade() -> None:
    # The original type is unrecoverable — the row that held it was deleted. A
    # blocked ``foe`` edge is the shape ADR-0009's motivating case took, so it is
    # the guess that loses the least.
    op.execute(
        """
        INSERT INTO relationship (from_character_id, to_character_id, type, status)
        SELECT blocker_character_id, blocked_character_id, 'foe', 'blocked'
        FROM character_block
        ON CONFLICT (from_character_id, to_character_id) DO NOTHING
        """
    )
    op.execute("DROP TABLE IF EXISTS character_block")
