"""Account deletion becomes a tombstone: a status value and a table (#2160).

Two carry-forwards, both for already-deployed databases only.

``accountstatus`` regains ``deleted``. The value was declared by the previous
baseline and dropped in the #1398 squash because nothing wrote it; ADR-0081 is
the flow that does, so it comes back with ``services.account_deletion`` behind
it. ``ADD VALUE IF NOT EXISTS`` because ``0002_squashed.ENUMS`` still builds a
fresh database with only ``active`` and ``suspended`` — that list is deliberately
frozen at the squash, and this revision is what a deployed database gets
instead.

``account_tombstone`` holds what outlives a deleted OAuth identity: the provider
in the clear and a salted SHA-256 of the identifier, unique on the pair, with
``created_at`` as the deletion timestamp the 90-day purge-on-access reads. See
``models/account.py``.

``0002_squashed`` builds tables straight from the ORM models, so on a fresh
database the table already exists by the time this runs — hence
``IF NOT EXISTS`` here too, the same shape every revision above the root uses.

``downgrade()`` drops the table and stops. Postgres cannot remove an enum
member, and inventing a ``DROP``/``CREATE``/rewrite dance for a value nothing
would be left to reference is more risk than the reversal is worth: the residue
is one unreachable label, which is the state the schema was already in before
the #1398 squash tidied it away.

Revision ID: 0015_account_tombstone
Revises: 0014_account_albescent_unlocked
Create Date: 2026-08-23
"""
from typing import Sequence, Union

from alembic import op

revision: str = "0015_account_tombstone"
down_revision: Union[str, None] = "0014_account_albescent_unlocked"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("ALTER TYPE accountstatus ADD VALUE IF NOT EXISTS 'deleted'")
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS account_tombstone (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            account_id BIGINT NOT NULL,
            provider VARCHAR NOT NULL,
            provider_user_hash VARCHAR NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
            CONSTRAINT pk_account_tombstone PRIMARY KEY (id),
            CONSTRAINT fk_account_tombstone_account_id_account
                FOREIGN KEY (account_id) REFERENCES account (id),
            CONSTRAINT uq_account_tombstone_provider_provider_user_hash
                UNIQUE (provider, provider_user_hash)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS account_tombstone")
