import { readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import { FACTION_RAINBOW_ORDER, factionCssVar } from "../factions";
import { sourceFiles } from "../../test/sourceScan";
import { stripComments } from "./cssVars";

/**
 * The reverse of `factionTokensDeclared.test.ts` (#2535).
 *
 * That guard walks references and asks whether each is declared. This one walks
 * DECLARATIONS and asks whether anything reads them, because the other failure
 * class is silent in a different way: an unread custom property is shipped
 * bytes in `index.css`, which is render-blocking, and nothing about it looks
 * wrong. #2535 found 23 — twelve of them the illustration palette of the gilt
 * WOW crest that #1989 retired, still describing a horn, a mane, a pupil and a
 * cheek for a drawing that no longer exists. They had been dead for weeks.
 *
 * WHY THIS CANNOT BE A NAIVE GREP. Two call sites build property names by
 * interpolation, so their targets are unreachable to any static sweep:
 *
 *   factions.ts        `--faction-${key}` / `--faction-${key}-${suffix}`
 *   Default/Albescent  `var(--spectrum-glow-${value})`, value 1-5
 *      Vote.tsx
 *
 * Both are encoded below as escape hatches. The faction one is generated by
 * calling the real `factionCssVar`, so it cannot drift from what the runtime
 * builds; adding a fourteenth suffix to `DYNAMIC_SUFFIXES` is all a new
 * contract rung needs.
 *
 * ponytail: a token whose ONLY reader is a test file still passes here, because
 * the sweep counts `__tests__` as sources — that is the method #2535 documents
 * and it keeps this rule at zero on a clean tree. It is not free: the stricter
 * sweep (references from non-test sources only) reports five more names, among
 * them `--faction-wow-vote-on` / `-off`, which nothing but `frozenThemeAliases`
 * has read since the vote caption row was struck in #2166. Upgrade path when
 * someone wants those bytes: drop `includeTests: true` from the `sourceFiles()` call and
 * carry the survivors as a named, dated allowlist.
 */

const SRC_DIR = join(fileURLToPath(new URL(".", import.meta.url)), "..", "..");

/** The namespaces this rule polices. Everything else is out of #2535's scope. */
const GOVERNED = /^--(faction|spectrum)-/;

/** Suffixes actually passed to `factionCssVar(slug, suffix)` across the app. */
const DYNAMIC_SUFFIXES = [
  // The accent, measured safe as ink on the page (#2619). Reached only as
  // `factionCssVar(slug, 'accent-ink')` — deliberately, because that is the
  // two-argument spelling `local/no-faction-hue-as-ink` does not fire on, so
  // there is no literal `var(--faction-…-accent-ink)` anywhere for a static
  // sweep to find and all eight rows read as dead without this entry.
  "accent-ink",
  "border",
  "card-accent",
  "card-bg",
  "card-border",
  "card-credit",
  "card-font",
  "card-muted",
  "card-notice",
  "card-radius",
  "card-text",
  "light",
  "on-accent",
  "on-fill",
];

/**
 * Every faction CSS key, straight out of the resolver. `na` is in the list
 * because it is what produces the `default` key — `albescent` maps there too
 * (ADR-0039, #783), which is why no `--faction-albescent-*` family exists and
 * why one must not be minted to satisfy this rule.
 */
const CSS_KEYS = [
  ...new Set(
    [...FACTION_RAINBOW_ORDER, "na"].map(
      (slug) => factionCssVar(slug).slice("var(".length, -1), // "--faction-<key>"
    ),
  ),
];

/** Names no static sweep can see, because a call site builds them at runtime. */
const DYNAMICALLY_BUILT = new Set([
  ...CSS_KEYS,
  ...CSS_KEYS.flatMap((base) =>
    DYNAMIC_SUFFIXES.map((suffix) => `${base}-${suffix}`),
  ),
  // vote/DefaultVote + vote/AlbescentVote, one per star value.
  ...[1, 2, 3, 4, 5].map((value) => `--spectrum-glow-${value}`),
]);

/**
 * This file is not a reader. It quotes token names as prose and as fixtures,
 * and a guard that counts its own assertions keeps alive exactly the tokens it
 * mentions — the first draft whitewashed `--spectrum-glow-4` that way.
 */
const SELF = fileURLToPath(import.meta.url);

/** A declaration: `--x: value`. Comments are stripped before this runs. */
const DECLARED_IN_CSS = /(?:^|[;{\s])(--[\w-]+)\s*:/g;
/** A `var()` reference; the trailing `[,)]` excludes interpolated names. */
const REFERENCE = /var\(\s*(--[A-Za-z0-9_-]+)\s*[,)]/g;
/** A bare literal — an inline-style key, a `setProperty`, a test's fixture. */
const QUOTED = /["'`](--[A-Za-z0-9_-]+)["'`]/g;

function matchAll(text: string, pattern: RegExp): string[] {
  return [...text.matchAll(pattern)].map((match) => match[1]);
}

/**
 * A token NAMED IN A COMMENT is not a reader — that is the whole trap this rule
 * exists to catch, and index.css is prose as much as it is paint: every one of
 * #2535's twelve crest names was described at length in the sheet that declared
 * it. So CSS comments are stripped before either sweep runs.
 *
 * TS/TSX are read RAW, and that is deliberate rather than lazy. `stripComments`
 * is the CSS-only stripper: run over a `.ts` file it pairs every `/*` with the
 * next `*​/` wherever they fall, including inside string literals and regexes,
 * and it silently ate a real `"--faction-snide-slip-pink-ink"` out of
 * `factionContrast.test.ts` when this guard first ran. A token mentioned only in
 * a JS docblock therefore counts as read here. That is the safe direction: this
 * rule DELETES things.
 */
const sources = sourceFiles({
  dir: SRC_DIR,
  includeTests: true,
  match: /\.(?:tsx?|jsx?|css)$/,
})
  .filter((path) => path !== SELF)
  .map((path) => {
    const text = readFileSync(path, "utf-8");
    return { path, text: path.endsWith(".css") ? stripComments(text) : text };
  });

const declared = new Map<string, string>();
for (const { path, text } of sources) {
  if (!path.endsWith(".css")) continue;
  for (const name of matchAll(text, DECLARED_IN_CSS)) {
    if (GOVERNED.test(name) && !declared.has(name)) declared.set(name, path);
  }
}

const referenced = new Set(
  sources.flatMap(({ text }) => [
    ...matchAll(text, REFERENCE),
    ...matchAll(text, QUOTED),
  ]),
);

describe("declared faction/spectrum tokens are read by something (#2535)", () => {
  it("finds the declarations it is meant to police (sanity check on the parse)", () => {
    expect(declared.size).toBeGreaterThan(300);
    expect(declared.has("--faction-singularity-card-muted")).toBe(true);
  });

  it("knows the names only a runtime interpolation can build", () => {
    // Eight slugs, seven distinct keys: albescent and na both land on default.
    expect(CSS_KEYS).toContain("--faction-default");
    expect(CSS_KEYS).not.toContain("--faction-albescent");
    expect(DYNAMICALLY_BUILT.has("--faction-coven-card-bg")).toBe(true);
    // Not literally present anywhere, yet read for every 4-star vote.
    expect(referenced.has("--spectrum-glow-4")).toBe(false);
    expect(DYNAMICALLY_BUILT.has("--spectrum-glow-4")).toBe(true);
  });

  it("has no declared token that nothing reads", () => {
    const unread = [...declared]
      .filter(
        ([name]) => !referenced.has(name) && !DYNAMICALLY_BUILT.has(name),
      )
      .map(([name, path]) => `${name} declared in ${path}, read by nothing`);

    expect(unread).toEqual([]);
  });
});
