import { existsSync, readFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve as resolvePath } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  factionRoleVar,
  type FactionGround,
  type FactionRole,
} from "../factionRoles";

/**
 * Guard for the silently-unloaded font family (#839).
 *
 * `fontFamily: "'Playfair Display', serif"` type-checks, lints, tokenises past
 * every ratchet and renders — as generic serif, because that family was never in
 * the loader. It had been that way for months across nine UA surfaces and no
 * check we run could see it: the fallback IS the rendering. Only comparing the
 * families named in source against the families the loader requests catches it.
 *
 * Sibling of factionTokensDeclared (#806) — same failure class, different half
 * of the stylesheet: a name that looks right and resolves to nothing.
 *
 * The reverse direction is a load-time guard rather than a rendering one. Every
 * family we ship is weight a visitor can pay whether or not anything uses it.
 * A family outlives the surface that introduced it — delete the last card that
 * named it and the woff2 stays behind, costing bytes forever and silently.
 * See docs/agents/load-time.md.
 *
 * SINCE #1977 THE LOADER IS OURS. The faces came from a render-blocking
 * `<link>` to fonts.googleapis.com and are now self-hosted `@font-face` rules
 * in `src/fonts.css`, generated by `scripts/fetch-fonts.mjs`. That moves one
 * failure mode INTO this repo: a `src:` path that does not match a file on disk
 * fails silently to a generic fallback — #839's bug wearing the delivery
 * mechanism's clothes, and the same one design-fidelity.md records from #821.
 * So there is a third question now, asked first: does every rule point at a
 * file that exists?
 *
 * SINCE #2079 THERE ARE TWO GENERATED SHEETS, and every question in this file is
 * asked of the pair. `fonts.css` holds the shell's three families (blocking);
 * `fonts.faction.css` holds the other fifteen, fetched by a faction chunk. WHICH
 * sheet a family is in is a different question and lives in
 * `factionFaceSplit.test.ts` — the questions here are "is it loaded at all" and
 * "at the weight something sets", and for those the two sheets are one loader.
 * Reading only `fonts.css` would report fifteen families as unloaded and every
 * faction surface as broken.
 */

const FRONTEND_DIR = join(fileURLToPath(new URL(".", import.meta.url)), "..", "..", "..");
const SRC_DIR = join(FRONTEND_DIR, "src");
const SOURCE_EXTENSIONS = [".ts", ".tsx", ".css"];

/**
 * The generated stylesheets are the LOADER, never a source that names families.
 *
 * They are `.css` files under `src/`, so `collectSourceFiles` would sweep them up
 * and every check below would then read the loader's own output as evidence
 * that the loader is right: "requests no family that nothing names" would pass
 * for all 18 by self-reference, and `declaredFaces` would report all 41 faces
 * as used because each `@font-face` block pins a family and a weight in one
 * brace scope. Three guards, vacuous at once. They must be excluded here and read
 * only through `loadedFaces`.
 */
const FONT_SHEETS = [join(SRC_DIR, "fonts.css"), join(SRC_DIR, "fonts.faction.css")];

/**
 * Generic CSS families and system-stack fallbacks. These are never loaded and
 * never need to be — they exist precisely to be the fallback.
 */
const GENERIC_FAMILIES = new Set([
  "serif",
  "sans-serif",
  "monospace",
  "cursive",
  "fantasy",
  "system-ui",
  "ui-monospace",
  "inherit",
  "initial",
  "unset",
  "georgia",
  "impact",
  "courier new",
  "marker felt",
  "menlo",
  "monaco",
  "consolas",
  "helvetica",
  "helvetica neue",
  "arial",
  "times new roman",
  "segoe ui",
  "trajan pro",
]);

function collectSourceFiles(directory: string): string[] {
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      // Tests quote family names as prose and fixtures.
      return entry.name === "__tests__" ? [] : collectSourceFiles(path);
    }
    if (FONT_SHEETS.includes(path)) return [];
    return SOURCE_EXTENSIONS.some((ext) => entry.name.endsWith(ext)) ? [path] : [];
  });
}

/** One `@font-face` block's body, in source order, across both sheets. */
function fontFaceBlocks(): string[] {
  return FONT_SHEETS.flatMap((sheet) =>
    [...readFileSync(sheet, "utf-8").matchAll(/@font-face\s*\{([^}]*)\}/g)].map(
      (match) => match[1],
    ),
  );
}

const blockField = (block: string, name: string): string | undefined =>
  block.match(new RegExp(`${name}\\s*:\\s*([^;]+);`))?.[1].trim();

/** The families the generated sheets actually ship an `@font-face` rule for. */
function loadedFamilies(): Set<string> {
  return new Set(
    fontFaceBlocks().map((block) =>
      (blockField(block, "font-family") ?? "").replace(/["']/g, "").trim().toLowerCase(),
    ),
  );
}

/**
 * Every quoted family name in a `font-family` / `fontFamily` declaration.
 * Quoted is the whole point: an unquoted token is either a generic keyword or a
 * `var()` reference, and `var()` chains land in index.css where the quoted name
 * ultimately appears anyway.
 */
function namedFamilies(source: string): string[] {
  const declarations = [...source.matchAll(/font-?[fF]amily\s*[:=]\s*([^;\n}]+)/g)]
    .map((match) => match[1])
    // A one-line style object puts the NEXT property on the same line
    // (`{ fontFamily: X, textTransform: "uppercase" }`), and a font-family list
    // is comma-separated too — so cut at the first comma that starts another
    // `property:` pair. Without this the guard "finds" families called
    // uppercase, nowrap and italic.
    .map((declaration) => declaration.split(/,\s*[A-Za-z-]+\s*:/)[0])
    // `factionCssVar("coven", "card-font")` builds a var() reference; its two
    // quoted arguments are a slug and a suffix, not families. `factionRoleVar`
    // is the same shape one level up (#2659) — a slug and a ROLE. Two lanes hit
    // it independently: #2680 put `factionRoleVar(slug, "face")` straight into a
    // `fontFamily:`, where the role name read as a missing family, and #2673
    // bound `UA_DISPLAY` to `factionRoleVar("ua", "face")`, whose two arguments
    // would be harvested as families called `ua` and `face`.
    .map((declaration) =>
      declaration.replace(/faction(?:CssVar|RoleVar)\([^)]*\)/g, ""),
    );
  return declarations.flatMap((declaration) =>
    [...declaration.matchAll(/["']([A-Za-z][A-Za-z0-9 ]+)["']/g)].map((match) =>
      match[1].trim().toLowerCase(),
    ),
  );
}

/**
 * Every `--font-*` token index.css declares, and the ones nothing reads (#1293).
 *
 * A token's own declaration carries the quoted family name and index.css is in
 * the corpus the family check searches, so before this every token vouched for
 * itself: declare `--font-faction-blackletter: "UnifrakturCook", …`, read it
 * nowhere, and the family stayed in the shipped font kit forever with the
 * guard green. The honest question is whether anything *reads* `var(--font-…)`.
 *
 * Still deliberately permissive in the other direction — a read counts wherever
 * it appears, including in a comment or a dead branch. Keeping a live token is
 * cheap; dropping one costs a silently-unstyled surface.
 */
function declaredFontTokens(): string[] {
  const css = readFileSync(join(SRC_DIR, "index.css"), "utf-8");
  return [...new Set([...css.matchAll(/(--font-[a-z0-9-]+)\s*:/g)].map((match) => match[1]))];
}

function unreadFontTokens(sources: string[]): string[] {
  return declaredFontTokens()
    .filter((token) => !sources.some((source) => source.includes(`var(${token})`)))
    .sort();
}

/** That source with the given tokens' declarations cut out of it. */
function withoutDeclarations(source: string, tokens: string[]): string {
  return tokens.reduce(
    (text, token) => text.replace(new RegExp(`${token}\\s*:[^;]*;`, "g"), ""),
    source,
  );
}

describe("font families are loaded (#839)", () => {
  const loaded = loadedFamilies();
  const sources = collectSourceFiles(SRC_DIR).map((file) =>
    readFileSync(file, "utf-8").toLowerCase(),
  );

  it("ships fonts at all (sanity check on the parse)", () => {
    expect(loaded.size).toBeGreaterThan(5);
    expect(loaded.has("bebas neue")).toBe(true);
  });

  it("points every @font-face at a file that exists (#1977)", () => {
    const sources = declaredSources();
    // A zero here is the parse having broken, not the stylesheet being clean.
    expect(sources.length).toBeGreaterThan(40);

    const dangling = sources.filter(({ path }) => !existsSync(path)).map(({ url }) => url);
    expect(
      dangling,
      `The generated font sheets point at ${dangling.join(", ")}, which is not on disk.
` +
        `Nothing fails: the browser drops the @font-face and the family renders in
` +
        `whatever generic the stack falls back to, which is the #821 defect
` +
        `(docs/agents/design-fidelity.md). Re-run 'node scripts/fetch-fonts.mjs'
` +
        `rather than hand-editing the path — the stylesheet is generated.`,
    ).toEqual([]);
  });

  it("names no family that the loader never requests", () => {
    const missing = new Set<string>();
    for (const file of [...collectSourceFiles(SRC_DIR)]) {
      for (const family of namedFamilies(readFileSync(file, "utf-8"))) {
        if (!GENERIC_FAMILIES.has(family) && !loaded.has(family)) {
          missing.add(`${family} (named in ${file})`);
        }
      }
    }
    expect([...missing]).toEqual([]);
  });

  it("declares no --font-* token that nothing reads", () => {
    const unread = unreadFontTokens(sources);

    expect(
      unread,
      `index.css declares ${unread.join(", ")}, which no source file reads.
` +
        `An unread family token is not inert: it names a family, index.css is in
` +
        `the corpus the family check searches, so the declaration vouches for
` +
        `itself and holds the family in the shipped font kit.
` +
        `Delete the token — and if it was the family's last reader, the family
` +
        `too (#1293).`,
    ).toEqual([]);
  });

  it("requests no family that nothing names", () => {
    // Deliberately a plain text search, not `namedFamilies`. That helper only
    // reads `font-family` declarations, but most families reach the page through
    // a custom property (`--font-faction-engraved: "Cinzel", serif`), which is
    // not one. For "is this family used at all?", any mention counts — and being
    // too permissive here only risks keeping a font, never dropping a live one.
    // The one mention that must NOT count is an unread token's own declaration:
    // that is the family naming itself (#1293), so those lines are cut first.
    const unread = unreadFontTokens(sources);
    const named = sources.map((source) => withoutDeclarations(source, unread));
    const unused = [...loaded]
      .filter((family) => !named.some((source) => source.includes(family)))
      .sort();

    expect(
      unused,
      `The generated font sheets ship ${unused.join(", ")}, which no source file names.
` +
        `A family nothing names is woff2 in the repo and @font-face bytes in the
` +
        `render-blocking stylesheet, for nothing. Drop it from FACES in
` +
        `scripts/fetch-fonts.mjs and re-run it — if a surface needs the family
` +
        `later, adding it back is one line and one re-run.`,
    ).toEqual([]);
  });
});

/**
 * The same guard one level down, at the axis spec (#1230).
 *
 * `loadedFamilies` parses `family=([^&"':]+)`, which stops at the colon — so
 * `Cinzel:wght@400;500;600;700;800` passed it identically whether five weights
 * were used or one. The families were honest and the request was still 46 faces
 * across 19 families; eight families accounted for 34 of them.
 *
 * A face is a separate download, so this is the same load-time bug as an unused
 * family, just finer-grained. It is also the same *rendering* bug in reverse:
 * drop a weight something actually sets and the browser does not fail, it
 * synthesises — a fake-bold that looks approximately right. So the evidence bar
 * here is higher than the family check's deliberately-permissive substring
 * search. A weight counts as used only when some brace-delimited scope pins both
 * the family and the weight; a mention in a comment or a dead branch does not.
 */

/** One downloadable face: a family at a weight, upright or italic. */
interface Face {
  family: string;
  weight: number;
  italic: boolean;
}

const faceKey = (face: Face): string =>
  `${face.family}:${face.weight}${face.italic ? "i" : ""}`;

/**
 * Every distinct face the generated sheets ship an `@font-face` rule for.
 *
 * Deduplicated across subsets: Anton has a `latin` rule and a `latin-ext` rule,
 * and those are one downloadable face split by `unicode-range`, not two. The
 * checks below reason about (family, weight, slant), which is the granularity a
 * `font-weight: 600` declaration in a skin can get wrong.
 */
function loadedFaces(): Face[] {
  const seen = new Map<string, Face>();
  for (const block of fontFaceBlocks()) {
    const face: Face = {
      family: (blockField(block, "font-family") ?? "").replace(/["']/g, "").trim().toLowerCase(),
      weight: Number(blockField(block, "font-weight") ?? 400),
      italic: blockField(block, "font-style") === "italic",
    };
    seen.set(faceKey(face), face);
  }
  return [...seen.values()];
}

/**
 * Every `src: url(...)` in the generated stylesheet, resolved against `src/`.
 *
 * The whole point of the check that uses this: a wrong path here does not
 * throw, warn or fail a build. The family resolves to a generic fallback and
 * the page looks plausible — see #821 in docs/agents/design-fidelity.md, where
 * two never-loaded fonts sat in production silently rendering as serif.
 */
function declaredSources(): { url: string; path: string }[] {
  return FONT_SHEETS.flatMap((sheet) =>
    [...readFileSync(sheet, "utf-8").matchAll(/src:\s*url\(\s*['"]?([^'")]+)/g)].map((match) => ({
      url: match[1],
      path: resolvePath(SRC_DIR, match[1]),
    })),
  );
}

/** Tailwind's three family utilities (tailwind.config.ts) and its weight scale. */
const TAILWIND_FAMILIES: Record<string, string> = {
  "font-display": "lora",
  "font-body": "courier prime",
  "font-accent": "bebas neue",
};
const TAILWIND_WEIGHTS: Record<string, number> = {
  "font-thin": 100,
  "font-extralight": 200,
  "font-light": 300,
  "font-normal": 400,
  "font-medium": 500,
  "font-semibold": 600,
  "font-bold": 700,
  "font-extrabold": 800,
  "font-black": 900,
};

/**
 * String `const` bindings a file can see: its own, plus the ones it imports.
 *
 * Every faction surface routes its family through one (`const CHROME =
 * "var(--font-faction-rounded)"`, then `fontFamily: CHROME`), and the shared
 * ones are imported rather than redeclared — UA's whole skin reads its two cuts
 * off `factionMarks/uaAtoms`. Resolving only local bindings misses those entirely.
 */
const bindingCache = new Map<string, Map<string, string>>();
function stringConstants(file: string, depth = 0): Map<string, string> {
  const cached = bindingCache.get(file);
  if (cached) return cached;
  const bindings = new Map<string, string>();
  bindingCache.set(file, bindings); // set first: import cycles are legal
  if (depth > 3 || !existsSync(file)) return bindings;
  const source = readFileSync(file, "utf-8");
  for (const match of source.matchAll(
    /(?:const|let)\s+([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=\s*(["'`])((?:(?!\2).)*)\2/g,
  )) {
    bindings.set(match[1], match[3]);
  }
  // A ROLE READ is a string constant whose value is not written in the source:
  // `const UA_DISPLAY = factionRoleVar("ua", "face")` (#2659). Resolve it
  // through the resolver itself rather than restating the role map here - a
  // second table is the drift that module exists to delete. Without this the
  // scope inlining loses the family behind every UA display cut, and the weight
  // guard demands the removal of a face eleven surfaces render in.
  for (const match of source.matchAll(
    /(?:const|let)\s+([A-Za-z_$][\w$]*)\s*(?::[^=]+)?=\s*factionRoleVar\(\s*["'`]([\w-]+)["'`]\s*,\s*["'`](\w+)["'`]\s*(?:,\s*["'`](\w+)["'`]\s*)?\)/g,
  )) {
    bindings.set(
      match[1],
      factionRoleVar(
        match[2],
        match[3] as FactionRole,
        (match[4] ?? "sheet") as FactionGround,
      ),
    );
  }
  for (const match of source.matchAll(/import\s*\{([^}]+)\}\s*from\s*["'](\.[^"']+)["']/g)) {
    const names = match[1]
      .split(",")
      .map((name) => name.trim().split(/\s+as\s+/).pop()?.trim() ?? "");
    for (const extension of [".ts", ".tsx", "/index.ts", "/index.tsx"]) {
      const target = resolvePath(dirname(file), match[2] + extension);
      if (!existsSync(target)) continue;
      const exported = stringConstants(target, depth + 1);
      for (const name of names) {
        const value = exported.get(name);
        if (value !== undefined && !bindings.has(name)) bindings.set(name, value);
      }
      break;
    }
  }
  return bindings;
}

/** That file's source with every such binding inlined at its use sites. */
function inlineConstants(file: string, source: string): string {
  const bindings = stringConstants(file);
  return source.replace(/\b([A-Za-z_$][\w$]*)\b/g, (name) => bindings.get(name) ?? name);
}

/** The innermost `{...}` around `index`, with nested blocks stripped out. */
function enclosingScope(source: string, index: number): string {
  // A JSX attribute's scope is its own TAG, not the brace block around it.
  // `<text fontFamily="IM Fell English, serif" fontStyle="italic">` sits inside
  // MediaArt's 12,000-character `switch` body, so every `fontWeight="700"`
  // anywhere in that body counted as this element's — inventing an IM Fell
  // English bold italic, a Bebas Neue bold italic and a Courier Prime bold
  // italic that no plate sets. Harmless while the guard only ever *kept* faces
  // (#1230); the direction below turns an invented face into a demand to load
  // one. Truncating early on an attribute value containing `>` would only drop
  // weights, which is the permissive direction.
  if (/^font-?[fF]amily\s*=\s*["']/.test(source.slice(index, index + 16))) {
    const start = source.lastIndexOf("<", index);
    const end = source.indexOf(">", index);
    if (start !== -1 && end !== -1) return source.slice(start, end);
  }
  let depth = 0;
  let start = -1;
  for (let cursor = index; cursor >= 0; cursor--) {
    if (source[cursor] === "}") depth++;
    else if (source[cursor] === "{") {
      if (depth === 0) {
        start = cursor;
        break;
      }
      depth--;
    }
  }
  if (start === -1) return source.slice(index, index + 200);
  depth = 0;
  let end = source.length;
  for (let cursor = start; cursor < source.length; cursor++) {
    if (source[cursor] === "{") depth++;
    else if (source[cursor] === "}") {
      depth--;
      if (depth === 0) {
        end = cursor;
        break;
      }
    }
  }
  // A child's weight must not count as the parent's, so keep depth-0 text only.
  let flat = "";
  depth = 0;
  for (const character of source.slice(start + 1, end)) {
    if (character === "{") depth++;
    else if (character === "}") depth--;
    else if (depth === 0) flat += character;
  }
  return flat;
}

/**
 * Every face a source file actually sets: each scope that pins a family, paired
 * with the weight and slant pinned alongside it. A scope that names a family and
 * no weight renders at the inherited default, which is 400 everywhere here — no
 * rule in the codebase sets a weight without also setting a family, bar
 * `.markdown-preview strong`, whose family is Lora via `@apply font-display`.
 */
function declaredFaces(loadedFamilyNames: Set<string>): Face[] {
  const declared: Face[] = [];
  const record = (families: Iterable<string>, weights: number[], italic: boolean) => {
    for (const family of families) {
      for (const weight of weights.length > 0 ? weights : [400]) {
        declared.push({ family, weight, italic });
      }
    }
  };

  for (const file of collectSourceFiles(SRC_DIR)) {
    const raw = readFileSync(file, "utf-8");
    const source = file.endsWith(".css") ? raw : inlineConstants(file, raw);

    for (const match of source.matchAll(/font-?[fF]amily\s*[:=]/g)) {
      const scope = enclosingScope(source, match.index);
      const families = new Set<string>();
      // Quoted in a stack, or bare before a comma in a JSX attribute
      // (`fontFamily="IM Fell English, serif"`).
      for (const quoted of scope.matchAll(/["']\s*([A-Za-z][A-Za-z0-9 ]+)\s*["',]/g)) {
        const family = quoted[1].trim().toLowerCase();
        if (loadedFamilyNames.has(family)) families.add(family);
      }
      for (const reference of scope.matchAll(/var\((--[a-z0-9-]+)\)/g)) {
        for (const family of familiesBehindToken(reference[1], loadedFamilyNames)) {
          families.add(family);
        }
      }
      if (families.size === 0) continue;

      const weights = [
        ...new Set(
          [...scope.matchAll(/font-?[wW]eight\s*[:=][^;\n]*/g)].flatMap((declaration) =>
            [...declaration[0].matchAll(/\b(\d{3})\b/g)].map((digits) => Number(digits[1])),
          ),
        ),
      ];
      record(families, weights, /font-?[sS]tyle\s*[:=]\s*\{?\s*["']?\s*italic/.test(scope));
    }

    // `className="font-display italic font-medium"` sets all three at once.
    for (const match of raw.matchAll(/(?:className\s*=\s*|@apply\s+)["'`]?([^"'`\n;]*)/g)) {
      const classes = match[1];
      const family = Object.entries(TAILWIND_FAMILIES).find(([utility]) =>
        new RegExp(`\\b${utility}\\b`).test(classes),
      )?.[1];
      if (!family) continue;
      const weight = Object.entries(TAILWIND_WEIGHTS).find(([utility]) =>
        new RegExp(`\\b${utility}\\b`).test(classes),
      )?.[1];
      record([family], weight === undefined ? [] : [weight], /\bitalic\b/.test(classes));
    }
  }
  return declared;
}

/** The loaded families a `var(--token)` resolves to, following alias chains. */
function familiesBehindToken(
  token: string,
  loadedFamilyNames: Set<string>,
  seen = new Set<string>(),
): string[] {
  if (seen.has(token)) return [];
  seen.add(token);
  const value = tokenValues().get(token);
  if (value === undefined) return [];
  const families = [...value.matchAll(/["']([^"']+)["']/g)]
    .map((match) => match[1].trim().toLowerCase())
    .filter((family) => loadedFamilyNames.has(family));
  for (const alias of value.matchAll(/var\((--[a-z0-9-]+)\)/g)) {
    families.push(...familiesBehindToken(alias[1], loadedFamilyNames, seen));
  }
  return families;
}

let tokenValueCache: Map<string, string> | undefined;
function tokenValues(): Map<string, string> {
  if (tokenValueCache) return tokenValueCache;
  const css = readFileSync(join(SRC_DIR, "index.css"), "utf-8");
  tokenValueCache = new Map();
  for (const match of css.matchAll(/(--[a-z0-9-]+)\s*:\s*([^;]+);/gi)) {
    // Light theme wins; the dark cascade never repoints a family token.
    if (!tokenValueCache.has(match[1])) tokenValueCache.set(match[1], match[2].trim());
  }
  return tokenValueCache;
}

/**
 * Which available weight a desired one actually renders as — CSS Fonts 4 §5.2.
 *
 * Not a nicety: a declared weight need not be requested to keep a face alive.
 * 22 `font-display` sites set no weight at all, so they ask for 400, and Lora is
 * requested at 500/600 — under this rule they render in the 500 face. Compare
 * requested against declared by equality and Lora 500 looks dead; drop it and
 * all 22 jump to 600. The guard has to resolve the way the browser does, or it
 * recommends deleting the very face a surface is rendering in.
 */
function matchedWeight(desired: number, available: number[]): number | undefined {
  if (available.includes(desired)) return desired;
  const descending = available.filter((w) => w < desired).sort((a, b) => b - a);
  const ascending = available.filter((w) => w > desired).sort((a, b) => a - b);
  if (desired < 400) return descending[0] ?? ascending[0];
  if (desired > 500) return ascending[0] ?? descending[0];
  // 400–500 inclusive: up to 500 first, then down, then past 500.
  const upToFiveHundred = ascending.filter((w) => w <= 500);
  return upToFiveHundred[0] ?? descending[0] ?? ascending[0];
}

describe("font weights are used (#1230)", () => {
  const faces = loadedFaces();
  const families = new Set(faces.map((face) => face.family));

  it("parses the axis spec, not just the family (sanity check)", () => {
    expect(faces.length).toBeGreaterThan(families.size);
    // A bare family is one upright face; `IM Fell English:ital@1` is one italic.
    expect(faces).toContainEqual({ family: "anton", weight: 400, italic: false });
    expect(faces).toContainEqual({ family: "im fell english", weight: 400, italic: true });
  });

  it("resolves a desired weight the way the browser does", () => {
    expect(matchedWeight(400, [500, 600])).toBe(500); // the Lora case
    expect(matchedWeight(700, [500, 600])).toBe(600);
    expect(matchedWeight(600, [400, 600])).toBe(600);
    expect(matchedWeight(500, [400, 700])).toBe(400);
  });

  it("requests no weight that nothing renders in", () => {
    const declared = declaredFaces(families);
    // Every face some declaration actually resolves to.
    const rendered = new Set<string>();
    for (const face of declared) {
      const available = faces
        .filter((candidate) => candidate.family === face.family && candidate.italic === face.italic)
        .map((candidate) => candidate.weight);
      const weight = matchedWeight(face.weight, available);
      if (weight !== undefined) rendered.add(faceKey({ ...face, weight }));
    }

    // A family with one face has no weight to get wrong — whatever the app sets,
    // that face is what renders. Redundant *faces within a family* are this
    // guard's business; a whole unused family is the family check's, above.
    const multiFace = new Set(
      [...families].filter(
        (family) => faces.filter((face) => face.family === family).length > 1,
      ),
    );
    const unused = faces
      .filter((face) => multiFace.has(face.family) && !rendered.has(faceKey(face)))
      .map((face) => `${face.family} ${face.weight}${face.italic ? " italic" : ""}`)
      .sort();

    expect(
      unused,
      `The generated font sheets ship ${unused.join(", ")}, which nothing renders in.
` +
        `Drop the axis value from the family's spec in FACES (scripts/fetch-fonts.mjs)
` +
        `and re-run it — the family stays, only the weight goes.
` +
        `No declaration resolves to it under CSS font matching, so removing it
` +
        `changes nothing on screen. If a surface really does use one, this guard
` +
        `could not see where: it counts a weight only when a single brace-scope
` +
        `pins both the family and the weight. Pin them together rather than
` +
        `widening the guard, or the fake-bold it exists to catch walks back in.`,
    ).toEqual([]);
  });
});

/**
 * The same axis, the other way round (#1294).
 *
 * #1230 asked "does anything render in this face?" and deleted the answers that
 * were no. It could not ask the converse — a weight a stylesheet sets and the
 * request omits does not fail, it *resolves*: 60 `--font-display` sites asked
 * for 400 and rendered in Lora 500, and 20 more asked for bold and rendered
 * semibold. Nothing on screen says so, which is #839's failure class one axis
 * down: a declaration that looks right and renders as something else.
 *
 * The owner's ruling (#1294) is that the stylesheet is the truth and the loader
 * follows it — where a surface declares a weight, that weight gets requested,
 * rather than the declaration being quietly rewritten to name whichever face the
 * browser happened to substitute.
 *
 * Resolution is CSS Fonts 4's, shared with the check above, so this is not a set
 * comparison: it asks what the browser would actually paint and objects only
 * when that is not what the source asked for.
 *
 * ponytail: this guards WEIGHT, not slant. A declared italic with no italic face
 * requested resolves against the family's upright — which is what the browser
 * does, synthesising the slant — and passes. Telling "this family has no italic"
 * from "this family has an italic we did not request" needs Google's catalogue,
 * which is a network call from a unit test. Bebas Neue is the live instance: it
 * ships one upright face, five na surfaces set `fontStyle: italic` on it, and
 * the oblique is synthetic on every one. Upgrade path is a checked-in catalogue
 * snapshot of the families we load, if a family ever gains an italic we miss.
 */
describe("used weights are requested (#1294)", () => {
  const faces = loadedFaces();
  const families = new Set(faces.map((face) => face.family));

  it("sees the weights source files actually set (sanity check)", () => {
    const declared = declaredFaces(families);
    expect(declared.length).toBeGreaterThan(100);
    // Lora at 700, via `--font-display` — reachable only by resolving the
    // token. This used to name WowSigil's Pig-Latin motto band as the live
    // instance; Sigil Studies v2 replaced that crest with a lettering-free
    // crown, and the weight is still declared by the `font-display font-bold`
    // headings the admin and About pages set.
    expect(declared).toContainEqual({ family: "lora", weight: 700, italic: false });
  });

  it("renders every declared weight in a face it requests", () => {
    const substituted = new Set<string>();
    for (const face of declaredFaces(families)) {
      // Slant is matched before weight (CSS Fonts 4 §5.2): with no italic face
      // the browser takes the family's upright and slants it itself, so those
      // are the faces the weight then resolves against.
      const sameSlant = faces.filter(
        (candidate) => candidate.family === face.family && candidate.italic === face.italic,
      );
      const available = (
        sameSlant.length > 0
          ? sameSlant
          : faces.filter((candidate) => candidate.family === face.family && !candidate.italic)
      ).map((candidate) => candidate.weight);
      const rendered = matchedWeight(face.weight, available);
      if (rendered !== face.weight) {
        substituted.add(
          `${face.family} ${face.weight}${face.italic ? " italic" : ""} renders as ${rendered ?? "no face"}`,
        );
      }
    }

    expect(
      [...substituted].sort(),
      `Source sets these weights and the generated font sheets do not ship them, so the
` +
        `browser substitutes: a real face at the wrong weight, or a synthesised
` +
        `fake-bold. Add the axis value to the family's spec in FACES
` +
        `(scripts/fetch-fonts.mjs) and re-run it — for a variable family that is
` +
        `usually not even another file, just another @font-face rule.
` +
        `If the family has no such face at all (Bebas Neue is upright 400 and
` +
        `nothing else), the declaration is the thing that is wrong: drop the
` +
        `weight rather than pretending the request can satisfy it (#1294).`,
    ).toEqual([]);
  });
});

/**
 * The INHERITED half of the same axis (#2487).
 *
 * #1294 counts a weight only where one brace-scope pins both the family and the
 * weight, and says so on purpose — widening the match is how a comment or a dead
 * branch starts inventing faces. That leaves one shape it cannot see, and the
 * shape is not rare: a composer puts its face on the whole surface through
 * `pageStyle`, and every style object below inherits it without naming it. Three
 * S.N.I.D.E. sites sat that way for months — `fontWeight: 700` on Special Elite,
 * which ships at 400 and nothing else — and #1294 read them as weights on no
 * family at all.
 *
 * The dress contract is what makes the inference safe here rather than a guess.
 * Each `*EditPraxis` archetype declares exactly one `pageStyle` naming exactly
 * one family, in the same file, and Tailwind's preflight resets headings AND
 * form controls to `font-weight: inherit` — so a weight in that file with no
 * family beside it is a weight on the page face. Nothing outside this directory
 * has an anchor that firm, which is why the walk stops here.
 *
 * It objects only to SYNTHESIS, not to substitution. A browser draws the bold
 * itself when a weight of 600 or more resolves to a face below 600 (CSS Fonts 4
 * §5.2.4), and that is the visible defect: a typewriter face smeared rather than
 * thickened. 700 landing on EB Garamond's real 600 is a substitution — arguably
 * wrong too, but that is a design call about which cut to draw, not a letterform
 * the browser invented, and this guard has no standing to make it.
 */
describe("an inherited page face is not asked to fake a bold (#2487)", () => {
  const COMPOSER_DIR = join(SRC_DIR, "pages", "editPraxis", "archetypes");
  const composers = readdirSync(COMPOSER_DIR).filter((name) => name.endsWith("EditPraxis.tsx"));
  const faces = loadedFaces();
  const familyNames = new Set(faces.map((face) => face.family));

  /**
   * The file with every comment blanked out, character for character.
   *
   * Prose about a weight is not a declaration of one, and this check reads a
   * file's whole text rather than only the scopes that pin a family — so the
   * paragraph in `SnideEditPraxis` explaining why it sets no `fontWeight: 700`
   * flagged itself the moment it was written. Blanking to spaces rather than
   * deleting keeps every index and line number exactly where it was, and takes
   * braces inside comments out of `enclosingScope`'s counting for free.
   */
  const readSource = (file: string): string =>
    inlineConstants(
      file,
      readFileSync(file, "utf-8").replace(
        /(["'`])(?:\\.|(?!\1)[^\\])*\1|\/\*[\s\S]*?\*\/|\/\/[^\n]*/g,
        (match) => (match.startsWith("/") ? match.replace(/[^\n]/g, " ") : match),
      ),
    );

  /** The families a composer's `pageStyle` puts on everything below it. */
  function pageFamilies(file: string): string[] {
    const source = readSource(file);
    const anchor = source.indexOf("pageStyle:");
    if (anchor === -1) return [];
    const offset = source.slice(anchor).search(/font-?[fF]amily\s*[:=]/);
    if (offset === -1) return [];
    return [...enclosingScope(source, anchor + offset).matchAll(/var\((--[a-z0-9-]+)\)/g)].flatMap(
      (reference) => familiesBehindToken(reference[1], familyNames),
    );
  }

  /** CSS Fonts 4 §5.2.4 — below 600 the browser has to draw the bold itself. */
  const synthesisesBold = (desired: number, used: number | undefined) =>
    desired >= 600 && (used === undefined || used < 600);

  it("resolves a page face wherever one is declared (sanity check on the anchor)", () => {
    expect(composers.length).toBeGreaterThan(1);
    for (const name of composers) {
      const file = join(COMPOSER_DIR, name);
      // Albescent is the archetype with no dress of its own: it wraps
      // `DefaultEditPraxis` in a class and declares no `pageStyle`, so there is
      // no face of its own to inherit and nothing here to check. Every other
      // one must resolve, or this guard is silently checking nothing.
      const declaresPageStyle = readSource(file).includes("pageStyle:");
      expect(pageFamilies(file).length > 0, `${name}: pageStyle anchor moved`).toBe(
        declaresPageStyle,
      );
    }
    expect(pageFamilies(join(COMPOSER_DIR, "SnideEditPraxis.tsx"))).toEqual(["special elite"]);
  });

  it("reads a comment about a weight as prose, not as a declaration", () => {
    const file = join(COMPOSER_DIR, "SnideEditPraxis.tsx");
    // That file's note explains, in so many words, the declaration it no longer
    // makes. A guard that cannot tell the explanation from the thing explained
    // reports its own documentation, so this is the live instance.
    expect(readFileSync(file, "utf-8")).toMatch(/fontWeight: 700/);
    expect(readSource(file)).not.toMatch(/font-?[wW]eight/);
  });

  it("knows a faked bold from a substituted one", () => {
    expect(synthesisesBold(700, matchedWeight(700, [400]))).toBe(true); // Special Elite
    expect(synthesisesBold(700, matchedWeight(700, [400, 600]))).toBe(false); // EB Garamond
    expect(synthesisesBold(500, matchedWeight(500, [400]))).toBe(false); // Poiret One
  });

  it("sets no unpinned weight the page face has to synthesise", () => {
    const faked: string[] = [];
    for (const name of composers) {
      const file = join(COMPOSER_DIR, name);
      const source = readSource(file);
      const page = pageFamilies(file);
      const available = faces
        .filter((face) => page.includes(face.family) && !face.italic)
        .map((face) => face.weight);
      for (const declaration of source.matchAll(/font-?[wW]eight\s*[:=][^;\n]*/g)) {
        // A scope that names its own family is #1294's business, not this one.
        if (/font-?[fF]amily/.test(enclosingScope(source, declaration.index))) continue;
        for (const digits of declaration[0].matchAll(/\b(\d{3})\b/g)) {
          const desired = Number(digits[1]);
          if (synthesisesBold(desired, matchedWeight(desired, available))) {
            // `inlineConstants` substitutes within a line, so the count holds.
            const line = source.slice(0, declaration.index).split("\n").length;
            faked.push(`${name}:${line} — fontWeight ${desired} inherits ${page.join(" / ")}`);
          }
        }
      }
    }

    expect(
      [...new Set(faked)].sort(),
      `These weights land on a face the loader ships no cut for, so the browser draws
` +
        `the bold itself — a smear across the letterforms rather than a heavier cut,
` +
        `and one no probe can see because the family still resolves (#2487).
` +
        `Drop the declaration and reach for emphasis the face supports — size,
` +
        `letterspacing, case, or the ink tier. Do NOT add the cut to the payload;
` +
        `the byte budget is already in WARN (#2469). If the element really is meant
` +
        `to wear a family that HAS the cut, name that family in the same style
` +
        `object: pinning them together is what makes the pair checkable.`,
    ).toEqual([]);
  });
});
