"""The declarative base, and the two schema-wide conventions every model obeys.

**Naming convention.** ``MetaData(naming_convention=...)`` gives every index,
unique constraint, check constraint, foreign key and primary key a deterministic
name derived from its table and columns, whether or not the model spells one
out. Without it Postgres names them and nothing in the repo can predict the
result, so a future ``ALTER``/``DROP CONSTRAINT`` has no stable target. That is
what makes this worth doing now: under Strategy B in
``docs/agents/db-migrations.md`` — the moment real data exists — a squash can no
longer rebuild the schema from scratch and every change becomes a named-object
edit. Adopted pre-launch, while renaming everything is free.

Models that already carry an explicit ``name=`` keep it verbatim; the convention
only fills in the blanks. The ``ck_`` pattern interpolates ``constraint_name``,
so a CHECK is declared with its *bare* name (``name="one_target"``) and comes
out as ``ck_<table>_one_target``.

**Integer identity columns.** Every surrogate primary key is
``BIGINT GENERATED BY DEFAULT AS IDENTITY``, and every foreign key pointing at
one is ``BIGINT`` to match:

* ``Identity()`` over ``SERIAL`` — PostgreSQL's own "Don't Do This" page names
  serial for its owned-sequence dependency and permission quirks; identity is
  the standard SQL form and the database manages it directly.
* ``BigInteger`` over ``Integer`` — insurance. Widening a live primary key plus
  every foreign key that references it rewrites half the database; doing it
  before any real row exists costs nothing.

``models/faction.py`` is the deliberate exception: its primary key is the
human-written ``slug`` string (ADR-0038), so ``faction_slug`` foreign keys are
strings, not bigints.

``backend/tests/unit/test_model_conventions.py`` enforces all of the above
across ``Base.metadata``, so a new model cannot quietly opt out;
``docs/agents/db-migrations.md`` carries the per-model inventory.
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# The convention set the Alembic docs recommend, with `column_0_N_name` so
# multi-column constraints name every column they cover.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
