#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Drives deploy/README.md sections 1, 2 and 5, and issue #3040. It does NOT
# restate the provisioning procedure: the implementation is deploy/bootstrap.sh,
# which this copies to the box and runs. A second copy of those steps here is
# how the two drift, and the copy that drifts is the one nobody runs.
#
# SECRETS: nothing secret is ever written to a file, echoed, or committed. The
# deploy key goes from ~/.ssh straight to `gh secret set` at the moment you run
# this. Only SSH_HOST is persisted, so re-runs can offer it back.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Derived from where THIS SCRIPT lives, never from the caller's cwd. The script
# sits at <repo>/scripts/, so the repo is one level up — which means it works
# run from anywhere, including $HOME. Deriving it from `pwd` looked fine when
# run from the repo and silently resolved to the wrong tree from anywhere else.
SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null) \
  || REPO_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
ENV_FILE="$REPO_ROOT/.claude/hetzner-provision.env"   # gitignored (/.claude/*)
mkdir -p "$(dirname "$ENV_FILE")"

KEY_PATH="$HOME/.ssh/wz_deploy"

# gh resolves "which repo?" from the CWD's git remote. Run this wizard from your
# home directory — the normal thing to do — and every gh call dies with "not a
# git repository", which the library's set_secret hides behind >/dev/null. That
# is how a run can report success while setting no secrets at all. GH_REPO makes
# gh cwd-independent; derived from the remote so it is not hardcoded here.
GH_REPO=$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null \
  | sed -E 's#^(git@|ssh://git@|https://)github\.com[:/]##; s#\.git$##')
export GH_REPO

# classify_ssh_failure STDERR: what kind of ssh failure was this? The seam
# stage 3 needs (#3052): ssh's own stderr is enough to tell a STALE known_hosts
# entry (recreating a Hetzner server can hand the same IPv4 a different host
# key) apart from a genuinely rejected key. Confusing the two sent someone
# deleting and recreating servers in a loop, which is what CAUSES the stale
# entry in the first place.
classify_ssh_failure() {
  local stderr="$1"
  if [[ "$stderr" == *"Host key verification failed"* \
     || "$stderr" == *"has changed and you have requested strict checking"* \
     || "$stderr" == *"Offending"*"key in"* ]]; then
    printf 'changed_host_key'
  elif [[ "$stderr" == *"Permission denied"* ]]; then
    printf 'auth_failed'
  else
    printf 'unknown'
  fi
}

# --self-test: fixture checks for classify_ssh_failure, no server needed.
# Runs before the banner so it never touches the terminal UX below.
if [[ "${1:-}" == "--self-test" ]]; then
  _st_pass=0; _st_fail=0
  _st_check() {
    local desc="$1" expected="$2" actual
    actual=$(classify_ssh_failure "$3")
    if [[ "$actual" == "$expected" ]]; then
      printf '  ok   - %s\n' "$desc"; _st_pass=$((_st_pass + 1))
    else
      printf '  FAIL - %s (expected %s, got %s)\n' "$desc" "$expected" "$actual" >&2
      _st_fail=$((_st_fail + 1))
    fi
  }

  _st_check "a changed host key reads as stale, not a rejected key" "changed_host_key" \
'Warning: the ECDSA host key for '"'"'5.78.227.180'"'"' differs from the key for the IP address.
Offending ED25519 key in /home/pixie/.ssh/known_hosts:14
Host key for 5.78.227.180 has changed and you have requested strict checking.
Host key verification failed.'

  _st_check "a genuine publickey rejection stays a rejection" "auth_failed" \
'deploy@5.78.227.180: Permission denied (publickey).'

  _st_check "unrecognised stderr classifies as unknown rather than guessing" "unknown" \
'ssh: connect to host 5.78.227.180 port 22: Connection timed out'

  printf '\n'
  if (( _st_fail )); then
    printf '%s%sself-test: %s failed, %s passed%s\n' "$BOLD" "$RED" "$_st_fail" "$_st_pass" "$RESET"
    exit 1
  fi
  printf '%s%sself-test: all %s checks passed%s\n' "$BOLD" "$GREEN" "$_st_pass" "$RESET"
  exit 0
fi

banner "World Zero: provision the Hetzner box"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
say "Checking this machine has what the later stages need."
missing=0
for tool in ssh scp ssh-keygen ssh-keyscan git gh; do
  if command -v "$tool" >/dev/null 2>&1; then
    note "  ✓ $tool"
  else
    warn "missing: $tool"; missing=1
  fi
done
if ! gh auth status >/dev/null 2>&1; then
  warn "gh is not authenticated — stage 6 cannot set secrets. Run: gh auth login"
  missing=1
elif [[ -z "$GH_REPO" ]]; then
  warn "could not work out the repo from $REPO_ROOT's origin remote."
  warn "Stage 6 cannot set secrets without it."
  missing=1
elif gh secret list >/dev/null 2>&1; then
  note "  ✓ gh authenticated and can reach $GH_REPO"
else
  warn "gh is authenticated but cannot read secrets on $GH_REPO."
  note "  Needs a token with 'repo' scope on a repo you admin: gh auth refresh -s repo"
  missing=1
fi
# Your personal key is very likely passphrase-protected, and the root/deploy
# tests below use `ssh -o BatchMode=yes`, which refuses to prompt. Without a
# reachable agent holding the key, every one of those fails with "could not log
# in" even on a perfectly healthy box with the key correctly installed. Catch
# that here rather than misdiagnosing it three stages later.
if ssh-add -l >/dev/null 2>&1; then
  note "  ✓ ssh-agent reachable, $(ssh-add -l 2>/dev/null | wc -l) key(s) loaded"
else
  if [[ -S "${SSH_AUTH_SOCK:-}" ]]; then
    warn "ssh-agent is reachable but holds no keys. Run: ssh-add"
  else
    warn "no ssh-agent in this shell (SSH_AUTH_SOCK is unset)."
    for sock in "/run/user/$(id -u)/ssh-agent.socket" "$XDG_RUNTIME_DIR/ssh-agent.socket"; do
      if [[ -S "$sock" ]]; then
        note "  Found an agent socket at $sock — try:"
        note "    export SSH_AUTH_SOCK=$sock"
        break
      fi
    done
    note "  Otherwise: eval \"\$(ssh-agent -s)\" && ssh-add"
  fi
  warn "A passphrase-protected key with no agent makes the root/deploy checks"
  warn "below fail even when the box and key are fine."
  missing=1
fi
if [[ -f "$REPO_ROOT/deploy/bootstrap.sh" ]]; then
  note "  ✓ deploy/bootstrap.sh found"
else
  warn "deploy/bootstrap.sh not found under $REPO_ROOT"
  warn "Run this from a checkout that has the deploy pipeline merged (PR #3046)."
  missing=1
fi
if (( missing )); then
  printf '\n'
  confirm "Some checks failed. Continue anyway?" || { echo "  Stopped."; exit 1; }
fi
pause "Preflight done. Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Create the server"
say "CPX11 (2 vCPU, 2 GB, x86, ~EUR 4.35/mo) is the floor; CPX21 (3 vCPU,"
say "4 GB, x86, ~EUR 8.50/mo) matches the 4 GB deploy/README.md assumes."
say "CX22 is EU-only -- CPX is the equivalent that also exists in US regions."
printf '\n'
step "Create a new server in the project you want it in."
step "Location: whichever is nearest your players."
step "Image: Ubuntu 24.04."
step "Type: SHARED vCPU -> x86 (Intel/AMD) -> CPX11 or CPX21."
warn "Take x86, NOT the cheaper CAX/ARM line. The GitHub runners are x86, and"
note "  cross-building the backend's Python wheels under emulation turns a"
note "  60-second build into ten minutes, on every merge, forever."
step "SSH keys: select your public key. Do this AT CREATE TIME, so the box"
note "  never has a root password at all."
step "Create, then copy its IPv4 address."
note "  Need more headroom later? Resize (CPX11 -> CPX21) rather than deleting"
note "  and recreating -- a resize is a reboot: same IPv4, same SSH host key."
note "  Recreating can hand the same IPv4 a DIFFERENT host key, which breaks"
note "  everyone's ~/.ssh/known_hosts and the pinned SSH_KNOWN_HOSTS secret."
printf '\n'
open_url "https://console.hetzner.cloud/"
ask SSH_HOST "Paste the server's IPv4 address:"
if [[ -z "${SSH_HOST:-}" ]]; then
  warn "No address given; cannot continue."; exit 1
fi
write_env SSH_HOST "$SSH_HOST"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Prove you can reach it as root"
say "This gate matters: the next stage disables root login and password auth."
say "If your key is not already working, that would lock you out of the box."
printf '\n'

# Is anything listening on 22? Distinguishes "wrong address / still booting"
# from "reachable, but rejected my key" — different problems, different fixes.
_port22_open() {
  timeout 6 bash -c "echo > /dev/tcp/$1/22" 2>/dev/null
}

# Hetzner Cloud gives every server a default reverse DNS under
# clients.your-server.de. If the rDNS is something else entirely, the address
# probably is not the server you just made.
_rdns() {
  getent hosts "$1" 2>/dev/null | awk '{print $2}' | head -1
}

# Captures stderr into LAST_SSH_STDERR (rather than discarding it) so the
# failure branch below can tell a stale known_hosts entry apart from a
# genuinely rejected key — see classify_ssh_failure above.
LAST_SSH_STDERR=""
_try_root() {
  local rc=0
  LAST_SSH_STDERR=$(ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 \
      -o PreferredAuthentications=publickey \
      "root@$1" true 2>&1 1>/dev/null) || rc=$?
  return "$rc"
}

# A bootstrapped box REFUSES root — that is the last thing bootstrap.sh does.
# Check for that FIRST. Without this, a re-run reads a correctly hardened server
# as a broken one and tells you to delete a working box.
BOOTSTRAPPED=0
if ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 \
       "deploy@$SSH_HOST" 'test -d /srv/worldzero' 2>/dev/null; then
  BOOTSTRAPPED=1
  printf '  %s✓%s deploy@%s works, and /srv/worldzero exists.\n' "$GREEN" "$RESET" "$SSH_HOST"
  printf '\n'
  say "This box is ALREADY bootstrapped, so root being refused is correct —"
  say "locking root out is the last thing bootstrap.sh does."
  warn "Do NOT delete this server. It is provisioned and reachable."
  note "  Skipping the root gate; there is nothing left for it to prove."
  printf '\n'
  pause "Press Enter."
fi

while (( BOOTSTRAPPED == 0 )); do
  note "  Trying: ssh -o BatchMode=yes root@$SSH_HOST true"
  if _try_root "$SSH_HOST"; then
    printf '  %s✓%s root login works.\n' "$GREEN" "$RESET"
    break
  fi

  printf '\n'
  warn "Could not log in as root with a key. Diagnosing..."
  printf '\n'

  if _port22_open "$SSH_HOST"; then
    note "  ✓ something IS listening on $SSH_HOST:22"
    reachable=1
  else
    printf '  %s✗%s nothing answered on %s:22\n' "$RED" "$RESET" "$SSH_HOST:22"
    reachable=0
  fi

  rdns=$(_rdns "$SSH_HOST")
  if [[ -n "$rdns" ]]; then
    note "  reverse DNS: $rdns"
    if [[ "$rdns" == *clients.your-server.de ]]; then
      note "    (that is Hetzner's default rDNS — the address looks right)"
    else
      warn "  that is NOT Hetzner's default rDNS (*.clients.your-server.de)."
      warn "  Double-check you pasted the server's own IPv4."
    fi
  else
    note "  reverse DNS: none found"
  fi

  if (( reachable == 0 )); then
    printf '\n'
    note "  Nothing on port 22 means SSH is not answering AT ALL — this is not a"
    note "  key problem, so recreating the server may not be the fix. Usually:"
    note "    - the box is still booting (give it a minute, then choose 2)"
    note "    - the server is POWERED OFF — check the console's power toggle"
    note "    - the address is not this server's"
    note "  If the reverse DNS above ends in clients.your-server.de, the address"
    note "  IS a Hetzner server, so look at power and boot state before deleting."
  else
    printf '\n'
    note "  NOTE: if this box has already been bootstrapped, root is SUPPOSED to"
    note "  be refused and nothing is wrong — but then deploy@ would have worked,"
    note "  so check that before believing anything below."
    printf '\n'

    failure_kind=$(classify_ssh_failure "$LAST_SSH_STDERR")
    if [[ "$failure_kind" == "changed_host_key" ]]; then
      note "  This is a STALE known_hosts entry, not a rejected key. ssh said:"
      printf '\n'
      while IFS= read -r line; do note "    $line"; done <<<"$LAST_SSH_STDERR"
      printf '\n'
      note "  Recreating a Hetzner server can hand the SAME IPv4 a DIFFERENT SSH"
      note "  host key. Your ~/.ssh/known_hosts still has the old one pinned, so"
      note "  ssh refuses to connect before authentication is even attempted —"
      note "  this has nothing to do with which key was selected at creation."
      warn "  Do NOT recreate the server over this. Recreating is what CAUSES a"
      warn "  stale entry, so following that advice loops: delete, recreate, same"
      warn "  message, delete again."
      note "  StrictHostKeyChecking=accept-new is doing its job — a CHANGED key is"
      note "  exactly the MITM case it exists to catch — so this stays on."
      printf '\n'
      note "  Also: if this server was just recreated or rebuilt, the SSH_KNOWN_HOSTS"
      note "  GitHub secret pins the OLD host key too, and CI will fail the same way"
      note "  with an equally confusing message until it's refreshed — stage 6 of"
      note "  this wizard re-runs ssh-keyscan and re-sets it for you."
      printf '\n'
      if confirm "Clear the stale entry now (ssh-keygen -R $SSH_HOST) and retry?"; then
        ssh-keygen -R "$SSH_HOST" >/dev/null 2>&1 || true
        note "  Cleared (backup kept at ~/.ssh/known_hosts.old). Retrying..."
        printf '\n'
        continue
      fi
    else
      note "  SSH is up but refused your key. Hetzner stores SSH keys ONLY at"
      note "  server-creation time — a key cannot be attached to a server that"
      note "  already exists. So if no key was selected when you created it, the"
      note "  fix is to recreate the server, not to adjust it."
      note "  https://docs.hetzner.com/cloud/servers/how-to-rescue/change-ssh-key/"
    fi
  fi

  printf '\n'
  say "What would you like to do?"
  step "1) Delete this server and create a new one, key attached (recommended)"
  step "2) Retry this address — it was just still booting"
  step "3) I have a different IP to try"
  step "4) Keep the box and repair it via Rescue mode + chroot"
  step "5) Continue anyway (NOT advised — stage 4 is one-way)"
  step "q) Quit"
  printf '\n  %sChoice:%s ' "$BOLD" "$RESET"
  read -r choice || true

  case "${choice:-}" in
    1)
      printf '\n'
      say "Delete and recreate. Nothing is on this box yet, so this is the"
      say "cheapest certain fix — and the only one that definitely attaches a key."
      printf '\n'
      open_url "https://console.hetzner.cloud/"
      step "Open the server, then its ... menu -> Delete -> confirm."
      step "Now create a new one: Ubuntu 24.04, SHARED vCPU -> x86 -> CPX11 or"
      note "    CPX21 (CX22 is EU-only; see stage 1)."
      warn "In the SSH keys section of the create form, TICK YOUR KEY."
      note "  This is the step that matters. If no key is selected, Hetzner emails"
      note "  a root password instead and you land right back here."
      note "  If your key is not listed at all, add it first:"
      note "    Security -> SSH keys -> Add SSH key, paste ~/.ssh/id_ed25519.pub"
      step "Create it, wait for it to finish booting, then copy the new IPv4."
      printf '\n'
      ask SSH_HOST "Paste the NEW server's IPv4 address:"
      write_env SSH_HOST "$SSH_HOST"
      ;;
    2)
      printf '\n'; note "  Waiting 20s, then retrying..."; sleep 20
      ;;
    3)
      printf '\n'
      ask SSH_HOST "Paste the IPv4 address to try:"
      write_env SSH_HOST "$SSH_HOST"
      ;;
    4)
      printf '\n'
      say "Rescue mode keeps the server and edits its authorized_keys directly."
      say "More steps than recreating, and only worth it if the box has state."
      printf '\n'
      open_url "https://console.hetzner.cloud/"
      step "Server -> Rescue -> 'Enable rescue & power cycle'. Note the rescue"
      note "    root password it shows you."
      step "ssh root@$SSH_HOST  (using that rescue password)"
      step "Then, on the box:"
      note "    lsblk                      # find the root partition, e.g. sda1"
      note "    mount /dev/sda1 /mnt"
      note "    chroot-prepare /mnt"
      note "    chroot /mnt"
      note "    nano /root/.ssh/authorized_keys   # append your public key"
      note "    exit"
      note "    reboot"
      printf '\n'
      note "  Your public key, to paste in:"
      if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
        printf '\n'; cat "$HOME/.ssh/id_ed25519.pub"; printf '\n'
      elif [[ -f "$HOME/.ssh/id_rsa.pub" ]]; then
        printf '\n'; cat "$HOME/.ssh/id_rsa.pub"; printf '\n'
      else
        warn "  no id_ed25519.pub or id_rsa.pub found in ~/.ssh"
      fi
      pause "Done? Press Enter to re-test."
      ;;
    5)
      warn "Continuing without proven root access. If bootstrap.sh cannot reach"
      warn "the box, nothing is provisioned; if it can but your key is not in"
      warn "root's authorized_keys, the deploy user gets no key and you lose access."
      confirm "Really continue?" && break
      ;;
    q|Q)
      echo "  Stopped. Re-run when ready; $SSH_HOST is remembered."; exit 0
      ;;
    *)
      warn "Unrecognised choice."
      ;;
  esac
  printf '\n'
done

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Run bootstrap.sh on the box"
say "This turns a fresh Ubuntu into a World Zero host. It:"
note "  - creates the 'deploy' user and installs Docker"
note "  - opens 22/80/443 and creates the 'edge' network"
note "  - creates /srv/worldzero/{edge,prod,dev} and /srv/backups"
note "  - installs the 04:00 backup cron"
note "  - LAST: disables root login and password authentication, then reads the"
note "    effective sshd config back and fails loudly if it did not take"
printf '\n'
warn "After this, root can no longer log in. The 'deploy' user is seeded with"
note "  root's authorized_keys, so your key still reaches the box. The script is"
note "  idempotent — it is safe to re-run."
printf '\n'
if (( BOOTSTRAPPED )); then
  say "Already bootstrapped. bootstrap.sh needs root, and root is locked out by"
  say "design, so it cannot and need not run again. Checking what it left behind."
  printf '\n'
  _dep() { ssh -o BatchMode=yes -o ConnectTimeout=15 "deploy@$SSH_HOST" "$@"; }
  for d in edge prod dev; do
    _dep "test -d /srv/worldzero/$d" 2>/dev/null \
      && note "  ✓ /srv/worldzero/$d" || warn "  missing /srv/worldzero/$d"
  done
  _dep 'docker --version' 2>/dev/null | sed 's/^/  ✓ /' || warn "  docker not working"

  # The cron is the one thing an aborted bootstrap leaves undone, and deploy can
  # repair it alone: the entry belongs to deploy, so `crontab -` needs no root.
  if _dep 'crontab -l 2>/dev/null | grep -q /srv/worldzero/backup.sh' 2>/dev/null; then
    note "  ✓ backup cron present"
  else
    warn "  backup cron is MISSING — repairing it as deploy (no root needed)"
    _dep 'bash -s' <<'CRONFIX'
set -eu
test -f /srv/worldzero/backup.sh || { echo "backup.sh is not on the box" >&2; exit 1; }
if ! crontab -l 2>/dev/null | grep -q '/srv/worldzero/backup.sh'; then
  { crontab -l 2>/dev/null || true
    echo '0 4 * * * /srv/worldzero/backup.sh prod'
  } | crontab -
fi
crontab -l | grep -q '/srv/worldzero/backup.sh'   && echo "  cron installed: $(crontab -l | grep backup.sh)"   || { echo "cron STILL missing" >&2; exit 1; }
CRONFIX
  fi
  printf '\n'
  pause "Press Enter."
elif ! confirm "Run bootstrap.sh on $SSH_HOST now?"; then
  echo "  Skipped — nothing was provisioned."
  pause "Press Enter."
elif [[ ! -f "$REPO_ROOT/deploy/bootstrap.sh" ]]; then
  warn "deploy/bootstrap.sh is missing under $REPO_ROOT — nothing was run."
  note "  This is the stage that provisions the box; it cannot be skipped."
  exit 1
else
  printf '\n'
  note "  Copying bootstrap.sh and backup.sh to /tmp on the box..."
  scp "$REPO_ROOT/deploy/bootstrap.sh" "$REPO_ROOT/deploy/backup.sh" "root@$SSH_HOST:/tmp/"
  printf '\n'
  note "  Running it. Output follows:"
  printf '\n'
  ssh "root@$SSH_HOST" 'bash /tmp/bootstrap.sh'
fi
printf '\n'
pause "Bootstrap finished. Press Enter."

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Mint the CI deploy key"
say "A key of its own, not yours. CI keys rotate on a different schedule than"
say "human keys, and this one has to be revocable without locking you out — by"
say "deleting one line from the box's authorized_keys."
printf '\n'
if [[ -f "$KEY_PATH" ]]; then
  note "  $KEY_PATH already exists; keeping it."
else
  note "  Creating $KEY_PATH"
  ssh-keygen -t ed25519 -f "$KEY_PATH" -N "" -C "github-actions-worldzero"
fi
printf '\n'
note "  Authorising it for deploy@$SSH_HOST"
if ssh-copy-id -i "${KEY_PATH}.pub" "deploy@$SSH_HOST" 2>&1 | tail -3; then
  printf '  %s✓%s key installed.\n' "$GREEN" "$RESET"
fi
if [[ ! -f "$KEY_PATH" ]]; then
  warn "$KEY_PATH was not created — cannot continue to the secrets stage."
  exit 1
fi
printf '\n'
note "  Verifying the key actually authenticates as deploy..."
if ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o IdentitiesOnly=yes \
       -i "$KEY_PATH" \
       "deploy@$SSH_HOST" 'docker ps >/dev/null && echo ok' 2>/dev/null | grep -q ok; then
  printf '  %s✓%s deploy@%s works and can reach Docker.\n' "$GREEN" "$RESET" "$SSH_HOST"
else
  warn "deploy@$SSH_HOST did not authenticate with that key, or cannot run docker."
  note "  CI will fail at the deploy step until this works."
fi
pause "Press Enter."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Set the three GitHub secrets"
say "These are the only three secrets GitHub holds. Every application secret"
say "lives in the .env files on the server and never passes through GitHub."
printf '\n'
note "  Values go straight from this machine to GitHub. Nothing is written to"
note "  disk, echoed, or committed."
printf '\n'
set_secret SSH_HOST "$SSH_HOST"
if [[ -f "$KEY_PATH" ]]; then
  set_secret SSH_PRIVATE_KEY "$(cat "$KEY_PATH")"
else
  warn "No key at $KEY_PATH; skipping SSH_PRIVATE_KEY."
  SKIPPED+=("GitHub secret SSH_PRIVATE_KEY")
fi
known_hosts=$(ssh-keyscan -t ed25519 "$SSH_HOST" 2>/dev/null || true)
if [[ -n "$known_hosts" ]]; then
  set_secret SSH_KNOWN_HOSTS "$known_hosts"
  note "  (pinned host key captured; CI refuses StrictHostKeyChecking=no — without"
  note "   the pin, the first thing answering on that IP gets a session that runs"
  note "   Docker as root)"
else
  warn "ssh-keyscan returned nothing for $SSH_HOST; skipping SSH_KNOWN_HOSTS."
  SKIPPED+=("GitHub secret SSH_KNOWN_HOSTS")
fi
printf '\n'
note "  DEPLOY_ENABLED is deliberately NOT set here. The pipeline stays switched"
note "  off until dev is ready — that is issue #3041."
pause "Press Enter."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Create the 'production' environment"
say "This is the human approval gate. Without it, a stray v* tag push ships to"
say "production unreviewed."
printf '\n'
open_url "https://github.com/pixieofhugs/WorldZeroPlayground/settings/environments"
step "New environment -> name it exactly: production"
step "Tick 'Required reviewers' and add yourself."
step "Under 'Deployment branches and tags', add a rule for: v*"
step "Save."
printf '\n'
note "  deploy.yml's prod job declares 'environment: production', so it pauses"
note "  here until you click approve."
pause "Done? Press Enter."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Bring up the edge proxy"
say "Caddy is the only thing on this box with a public port. It is deployed by"
say "hand, never by CI, so a broken app deploy can never take TLS down with it."
printf '\n'
warn "Certificates will NOT issue yet, and that is expected."
note "  Let's Encrypt validates over HTTP-01, which needs DNS already pointing"
note "  at this box. DNS is issue #3041. Caddy will retry on its own and start"
note "  serving certificates the moment the records land. Errors in its log"
note "  before then are not a fault."
printf '\n'
confirm "Copy the edge config and start Caddy on $SSH_HOST?" && {
  ssh "deploy@$SSH_HOST" 'mkdir -p /srv/worldzero/edge'
  scp "$REPO_ROOT/deploy/edge.docker-compose.yml" \
      "deploy@$SSH_HOST:/srv/worldzero/edge/docker-compose.yml"
  scp "$REPO_ROOT/deploy/Caddyfile" "deploy@$SSH_HOST:/srv/worldzero/edge/Caddyfile"
  ssh "deploy@$SSH_HOST" 'cd /srv/worldzero/edge && docker compose -p edge up -d'
  printf '\n'
  ssh "deploy@$SSH_HOST" 'docker compose -p edge ps' || true
}
pause "Press Enter."

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Verify"
say "Running issue #3040's done-when checks against the box."
printf '\n'
pass=0; fail=0
check() {
  local label="$1"; shift
  if "$@" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$label"; pass=$((pass+1))
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$label"; fail=$((fail+1))
  fi
}
# IdentitiesOnly=yes is what makes this a test of the CI KEY. Without it, ssh
# offers the agent's keys too, so these checks pass via your personal key even
# when $KEY_PATH does not exist — which is exactly how a run once reported a
# fully provisioned box with no CI key on it.
_deploy_ssh() {
  ssh -o BatchMode=yes -o ConnectTimeout=15 -o IdentitiesOnly=yes \
      -i "$KEY_PATH" "deploy@$SSH_HOST" "$@"
}

check "deploy@$SSH_HOST can run docker"        _deploy_ssh 'docker ps'
check "/srv/worldzero/{edge,prod,dev} exist"   _deploy_ssh 'test -d /srv/worldzero/edge -a -d /srv/worldzero/prod -a -d /srv/worldzero/dev'
check "/srv/backups exists"                    _deploy_ssh 'test -d /srv/backups'
check "backup cron installed"                  _deploy_ssh 'crontab -l | grep -q backup.sh'
check "edge network exists"                    _deploy_ssh 'docker network inspect edge'
check "edge-caddy is running"                  _deploy_ssh 'docker ps --format "{{.Names}}" | grep -q edge-caddy'
check "ports 80 and 443 are listening"         _deploy_ssh 'ss -ltn | grep -qE ":(80|443) "'

# Root must be REFUSED. Inverted on purpose: success here is a failed login.
printf '  ... checking root is locked out\n'
if ssh -o BatchMode=yes -o ConnectTimeout=15 -o PreferredAuthentications=publickey \
       "root@$SSH_HOST" true 2>/dev/null; then
  printf '  %s✗%s root can still log in — bootstrap hardening did not take\n' "$RED" "$RESET"
  fail=$((fail+1))
else
  printf '  %s✓%s root login refused\n' "$GREEN" "$RESET"; pass=$((pass+1))
fi

# Password auth, read off the box itself.
printf '  ... checking password auth is off\n'
pw=$(_deploy_ssh 'sudo -n sshd -T 2>/dev/null | grep "^passwordauthentication " || sshd -T 2>/dev/null | grep "^passwordauthentication "' 2>/dev/null || true)
if [[ "$pw" == "passwordauthentication no" ]]; then
  printf '  %s✓%s passwordauthentication no\n' "$GREEN" "$RESET"; pass=$((pass+1))
elif [[ -z "$pw" ]]; then
  printf '  %s!%s could not read sshd config as deploy (needs root) — bootstrap.sh\n' "$YELLOW" "$RESET"
  printf '    already asserted this with sshd -T and would have exited non-zero.\n'
else
  printf '  %s✗%s sshd reports: %s\n' "$RED" "$RESET" "$pw"; fail=$((fail+1))
fi

printf '\n'
if (( fail )); then
  warn "$fail check(s) failed, $pass passed. Fix these before issue #3041."
else
  printf '  %s%sAll %s checks passed.%s\n' "$BOLD" "$GREEN" "$pass" "$RESET"
fi
printf '\n'
note "  Next: issue #3041 — DNS for dev + api.dev, the OAuth console redirect"
note "  URIs, /srv/worldzero/dev/.env, then set DEPLOY_ENABLED=true to arm the"
note "  pipeline and merge to main."
pause "Press Enter for the summary."

finish
